import type { AproximadoQuestion } from "./aproximado.rules";

type Locale = "es" | "en" | "ka" | "tr";
type Kind = AproximadoQuestion["kind"];

const es = {
  brandA: "Aproximado",
  brandB: "futbolero",
  round: (n: number, total: number) => `Pregunta ${n}/${total}`,
  seconds: (s: number) => `${s} s`,
  kinds: { fee: "Traspaso", value: "Valor de mercado", goals: "Goles", attendance: "Público", height: "Altura", apps: "Partidos", age: "Edad" } as Record<Kind, string>,
  inputLabel: "Tu número",
  inputHint: "El que más se acerque suma. El exacto, +1.",
  invalid: "Escribí un número.",
  confirm: "Confirmar",
  you: "Vos",
  answered: "Respondió",
  thinking: "Pensando…",
  away: "Desconectado",
  withdrawn: "Se fue",
  idle: "Ausente",
  waiting: (n: number) => (n === 1 ? "Esperando a 1 jugador…" : `Esperando a ${n} jugadores…`),
  revealing: "¡Todos respondieron! Revelando…",
  yourGuess: (v: string) => `Tu respuesta: ${v}`,
  itWas: "Era",
  off: (v: string) => `a ${v}`,
  exact: "¡Exacto!",
  noGuess: "Sin respuesta",
  pts: (n: number) => `+${n}`,
  roundWinner: (name: string) => `${name} se llevó la ronda`,
  youWonRound: "¡Te llevaste la ronda!",
  roundTie: "Empate arriba",
  nobody: "Nadie respondió",
  introTitle: (n: number) => (n === 2 ? "1 contra 1" : `${n} jugadores`),
  introRules: (top: number) => [
    "10 preguntas de números del fútbol: traspasos, goles, público…",
    "Escribí tu número antes de que termine el reloj. Nadie ve tu respuesta hasta el final de la ronda.",
    top === 1 ? "El más cercano suma 1 punto. El exacto, +1." : `El más cercano suma ${top}, el siguiente ${top - 1}… El exacto, +1.`,
  ],
  startsIn: (s: number) => `Arranca en ${s}`,
  finalTitle: "Resultado final",
  youWon: "¡Ganaste!",
  youPlace: (p: number) => `Quedaste ${p}º`,
  tieFirst: "¡Empate en el primer puesto!",
  colPoints: "Pts",
  colWins: "Rondas ganadas",
  resultDetail: (wins: number, error: number) => `${wins} ${wins === 1 ? "ronda ganada" : "rondas ganadas"} · error medio ${error}%`,
  colError: "Error medio",
  backToRoom: "Volver a la sala",
  exit: "Salir",
  scoringPodium: "Podio (3-2-1)",
  scoringClosest: "Solo el más cercano",
  colPlayer: "Jugador",
  cancelledTitle: "Partida cancelada",
  cancelledText: "No quedaron jugadores suficientes para jugar.",
  hurry: "¡Quedan 5 segundos!",
  answeredOf: (a: number, b: number) => `${a} de ${b} respondieron`,
  willSend: (v: string) => `Vas a mandar ${v}`,
  sending: "Enviando",
  waitingClock: "Esperando que termine el tiempo…",
  leave: "Salir de la partida",
  leaveConfirm: "¿Salir de la partida? No vas a poder volver a entrar.",
  leaveYes: "Salir",
  leaveNo: "Seguir jugando",
  offline: "Sin conexión: reconectando… Tu respuesta se puede mandar cuando vuelvas, si la pregunta sigue abierta.",
  errors: { stale_round: "Esa pregunta ya pasó.", excluded: "La partida arrancó sin vos.", not_active: "La partida no está en juego.", rate_limited: "Demasiado rápido. Esperá un momento.", room_not_found: "Esta partida no existe o ya terminó.", not_in_match: "No estás en esta partida.", not_open: "Esa pregunta ya se cerró.", already_answered: "Ya respondiste esta pregunta.", withdrawn: "Ya saliste de la partida.", invalid: "Ese número no vale para esta pregunta.", default: "No se pudo mandar. Probá de nuevo." } as Record<string, string>,
  youLeftTitle: "Saliste de la partida",
  youLeftText: "Tus respuestas cuentan, pero quedás debajo de los que terminaron.",
  excludedTitle: "La partida arrancó sin vos",
  excludedText: "No confirmaste a tiempo. Podés esperar en la sala a la próxima.",
  gateTitle: "Esperando a que todos entren…",
  gateReady: "Listo",
  gateWaiting: "Entrando…",
  connecting: "Conectando…",
  retry: "Reintentar",
  finishedTitle: "Partida terminada",
  finishedText: "Esta partida ya terminó.",
};

type Copy = typeof es;

const en: Copy = {
  ...es,
  brandA: "Closest",
  brandB: "Wins",
  round: (n, total) => `Question ${n}/${total}`,
  kinds: { fee: "Transfer fee", value: "Market value", goals: "Goals", attendance: "Crowd", height: "Height", apps: "Appearances", age: "Age" },
  inputLabel: "Your number",
  inputHint: "Closest scores. Exact, +1.",
  invalid: "Type a number.",
  confirm: "Lock it in",
  you: "You",
  answered: "Answered",
  thinking: "Thinking…",
  away: "Disconnected",
  withdrawn: "Left",
  idle: "Away",
  waiting: (n) => (n === 1 ? "Waiting for 1 player…" : `Waiting for ${n} players…`),
  revealing: "Everyone's in! Revealing…",
  yourGuess: (v) => `Your answer: ${v}`,
  itWas: "It was",
  off: (v) => `${v} off`,
  exact: "Bullseye!",
  noGuess: "No answer",
  roundWinner: (name) => `${name} takes the round`,
  youWonRound: "You take the round!",
  roundTie: "Tie at the top",
  nobody: "Nobody answered",
  introTitle: (n) => (n === 2 ? "1 vs 1" : `${n} players`),
  introRules: (top) => [
    "10 football number questions: fees, goals, crowds…",
    "Type your number before the clock ends. Nobody sees your answer until the round ends.",
    top === 1 ? "Closest scores 1 point. Exact, +1." : `Closest scores ${top}, the next ${top - 1}… Exact, +1.`,
  ],
  startsIn: (s) => `Starts in ${s}`,
  finalTitle: "Final result",
  youWon: "You won!",
  youPlace: (p) => `You finished #${p}`,
  tieFirst: "Tied for first!",
  colPoints: "Pts",
  colWins: "Rounds won",
  resultDetail: (wins, error) => `${wins} ${wins === 1 ? "round" : "rounds"} won · avg error ${error}%`,
  colError: "Avg error",
  backToRoom: "Back to the room",
  exit: "Exit",
  scoringPodium: "Podium (3-2-1)",
  scoringClosest: "Closest only",
  colPlayer: "Player",
  cancelledTitle: "Match cancelled",
  cancelledText: "Not enough players were left to play.",
  hurry: "5 seconds left!",
  answeredOf: (a, b) => `${a} of ${b} answered`,
  willSend: (v) => `You will send ${v}`,
  sending: "Sending",
  waitingClock: "Waiting for the clock…",
  leave: "Leave the match",
  leaveConfirm: "Leave the match? You won't be able to come back in.",
  leaveYes: "Leave",
  leaveNo: "Keep playing",
  offline: "Connection lost: reconnecting… You can still answer when you're back, if the question is open.",
  errors: { stale_round: "That question is over.", excluded: "The match started without you.", not_active: "The match isn't in play.", rate_limited: "Too fast. Wait a moment.", room_not_found: "This match doesn't exist or has ended.", not_in_match: "You're not in this match.", not_open: "That question has closed.", already_answered: "You already answered this question.", withdrawn: "You already left the match.", invalid: "That number isn't valid for this question.", default: "Couldn't send it. Try again." },
  youLeftTitle: "You left the match",
  youLeftText: "Your answers count, but you rank below everyone who finished.",
  excludedTitle: "The match started without you",
  excludedText: "You didn't confirm in time. Wait in the room for the next one.",
  gateTitle: "Waiting for everyone to join…",
  gateReady: "Ready",
  gateWaiting: "Joining…",
  connecting: "Connecting…",
  retry: "Retry",
  finishedTitle: "Match over",
  finishedText: "This match has already ended.",
};

const ka: Copy = {
  ...en,
  // Same names as the live daily (messages play.statSniperTitle).
  brandA: "სტატ",
  brandB: "სნაიპერი",
  round: (n, total) => `კითხვა ${n}/${total}`,
  kinds: { fee: "ტრანსფერი", value: "საბაზრო ღირებულება", goals: "გოლები", attendance: "მაყურებელი", height: "სიმაღლე", apps: "მატჩები", age: "ასაკი" },
  inputLabel: "შენი რიცხვი",
  inputHint: "ყველაზე ახლოს მყოფი იღებს ქულას. ზუსტი პასუხი, +1.",
  invalid: "ჩაწერე რიცხვი.",
  confirm: "დადასტურება",
  you: "შენ",
  answered: "უპასუხა",
  thinking: "ფიქრობს…",
  away: "გაითიშა",
  withdrawn: "წავიდა",
  idle: "არ არის",
  waiting: (n) => `ველოდებით ${n} მოთამაშეს…`,
  revealing: "ყველამ უპასუხა! ვხსნით…",
  yourGuess: (v) => `შენი პასუხი: ${v}`,
  itWas: "სწორი",
  off: (v) => `სხვაობა ${v}`,
  exact: "ზუსტად!",
  noGuess: "პასუხის გარეშე",
  roundWinner: (name) => `რაუნდი მოიგო ${name}-მ`,
  youWonRound: "რაუნდი შენ მოიგე!",
  roundTie: "თანაბრად პირველები",
  nobody: "არავინ უპასუხა",
  introTitle: (n) => (n === 2 ? "1 1-ზე" : `${n} მოთამაშე`),
  introRules: (top) => [
    "10 კითხვა ფეხბურთის რიცხვებზე: ტრანსფერები, გოლები, მაყურებელი…",
    "ჩაწერე რიცხვი სანამ დრო ამოიწურება. რაუნდის ბოლომდე შენს პასუხს ვერავინ ხედავს.",
    top === 1 ? "ყველაზე ახლოს მყოფი იღებს 1 ქულას. ზუსტი, +1." : `ყველაზე ახლოს მყოფი იღებს ${top}-ს, შემდეგი ${top - 1}-ს… ზუსტი, +1.`,
  ],
  startsIn: (s) => `იწყება ${s}-ში`,
  finalTitle: "საბოლოო შედეგი",
  youWon: "მოიგე!",
  youPlace: (p) => `შენ ხარ ${p}-ე`,
  tieFirst: "თანაბრად პირველ ადგილზე!",
  colPoints: "ქულა",
  colWins: "მოგებული რაუნდი",
  resultDetail: (wins, error) => `მოგებული რაუნდი: ${wins} · საშ. შეცდომა ${error}%`,
  colError: "საშ. შეცდომა",
  backToRoom: "ოთახში დაბრუნება",
  exit: "გასვლა",
  colPlayer: "მოთამაშე",
  cancelledTitle: "მატჩი გაუქმდა",
  cancelledText: "თამაშისთვის საკმარისი მოთამაშე აღარ დარჩა.",
  hurry: "დარჩა 5 წამი!",
  answeredOf: (a, b) => `${b}-დან ${a}-მა უპასუხა`,
  willSend: (v) => `გაიგზავნება ${v}`,
  sending: "იგზავნება",
  waitingClock: "ველოდებით დროის ამოწურვას…",
  leave: "მატჩიდან გასვლა",
  leaveConfirm: "გახვალ მატჩიდან? უკან ვეღარ დაბრუნდები.",
  leaveYes: "გასვლა",
  leaveNo: "თამაშის გაგრძელება",
  offline: "კავშირი გაწყდა: ვცდილობთ დაკავშირებას… დაბრუნების შემდეგ პასუხს გაგზავნი, თუ კითხვა ჯერ ღიაა.",
  errors: { stale_round: "ეს კითხვა უკვე დასრულდა.", excluded: "მატჩი შენს გარეშე დაიწყო.", not_active: "მატჩი არ მიმდინარეობს.", rate_limited: "ძალიან სწრაფად. ცოტა მოიცადე.", room_not_found: "ეს მატჩი არ არსებობს ან დასრულდა.", not_in_match: "ამ მატჩში არ ხარ.", not_open: "ეს კითხვა უკვე დაიხურა.", already_answered: "ამ კითხვას უკვე უპასუხე.", withdrawn: "მატჩიდან უკვე გახვედი.", invalid: "ეს რიცხვი ამ კითხვისთვის არ ვარგა.", default: "ვერ გაიგზავნა. სცადე თავიდან." },
  youLeftTitle: "მატჩიდან გახვედი",
  youLeftText: "შენი პასუხები ითვლება, მაგრამ დამამთავრებლების ქვემოთ ხარ.",
  excludedTitle: "მატჩი შენს გარეშე დაიწყო",
  excludedText: "დროულად არ დაადასტურე. ოთახში დაელოდე შემდეგს.",
  gateTitle: "ველოდებით, რომ ყველა შემოვიდეს…",
  gateReady: "მზადაა",
  gateWaiting: "შემოდის…",
  connecting: "დაკავშირება…",
  retry: "თავიდან ცდა",
  finishedTitle: "მატჩი დასრულდა",
  finishedText: "ეს მატჩი უკვე დასრულდა.",
};

const tr: Copy = {
  ...en,
  brandA: "En Yakın",
  brandB: "Tahmin",
  round: (n, total) => `Soru ${n}/${total}`,
  kinds: { fee: "Bonservis", value: "Piyasa değeri", goals: "Gol", attendance: "Seyirci", height: "Boy", apps: "Maç", age: "Yaş" },
  inputLabel: "Tahminin",
  inputHint: "En yakın olan puan alır. Tam isabet, +1.",
  invalid: "Bir sayı yaz.",
  confirm: "Onayla",
  you: "Sen",
  answered: "Cevapladı",
  thinking: "Düşünüyor…",
  away: "Bağlantı koptu",
  withdrawn: "Ayrıldı",
  idle: "Uzakta",
  waiting: (n) => `${n} oyuncu bekleniyor…`,
  revealing: "Herkes cevapladı! Açıklanıyor…",
  yourGuess: (v) => `Cevabın: ${v}`,
  itWas: "Doğrusu",
  off: (v) => `${v} fark`,
  exact: "Tam isabet!",
  noGuess: "Cevap yok",
  roundWinner: (name) => `Turu ${name} aldı`,
  youWonRound: "Turu sen aldın!",
  roundTie: "Zirvede eşitlik",
  nobody: "Kimse cevaplamadı",
  introTitle: (n) => (n === 2 ? "1'e 1" : `${n} oyuncu`),
  introRules: (top) => [
    "Futbol sayılarıyla ilgili 10 soru: bonservisler, goller, seyirci…",
    "Süre bitmeden sayını yaz. Tur bitene kadar kimse cevabını görmez.",
    top === 1 ? "En yakın olan 1 puan alır. Tam isabet, +1." : `En yakın olan ${top}, sonraki ${top - 1} puan alır… Tam isabet, +1.`,
  ],
  startsIn: (s) => `${s} saniye sonra başlıyor`,
  finalTitle: "Final sonucu",
  youWon: "Kazandın!",
  youPlace: (p) => `${p}. oldun`,
  tieFirst: "Birincilikte eşitlik!",
  colPoints: "Puan",
  colWins: "Kazanılan tur",
  resultDetail: (wins, error) => `${wins} tur kazandı · ort. hata %${error}`,
  colError: "Ort. hata",
  backToRoom: "Odaya dön",
  exit: "Çık",
  scoringPodium: "Podyum (3-2-1)",
  scoringClosest: "Sadece en yakın",
  colPlayer: "Oyuncu",
  cancelledTitle: "Maç iptal edildi",
  cancelledText: "Oynamak için yeterli oyuncu kalmadı.",
  hurry: "5 saniye kaldı!",
  answeredOf: (a, b) => `${b} oyuncudan ${a} cevapladı`,
  willSend: (v) => `Gönderilecek: ${v}`,
  sending: "Gönderiliyor",
  waitingClock: "Sürenin bitmesi bekleniyor…",
  leave: "Maçtan çık",
  leaveConfirm: "Maçtan çıkılsın mı? Geri giremezsin.",
  leaveYes: "Çık",
  leaveNo: "Oynamaya devam et",
  offline: "Bağlantı koptu: yeniden bağlanılıyor… Döndüğünde soru hâlâ açıksa cevap gönderebilirsin.",
  errors: { stale_round: "Bu soru bitti.", excluded: "Maç sensiz başladı.", not_active: "Maç oynanmıyor.", rate_limited: "Çok hızlı. Biraz bekle.", room_not_found: "Bu maç yok ya da bitti.", not_in_match: "Bu maçta değilsin.", not_open: "Bu soru kapandı.", already_answered: "Bu soruyu zaten cevapladın.", withdrawn: "Maçtan zaten çıktın.", invalid: "Bu sayı bu soru için geçerli değil.", default: "Gönderilemedi. Tekrar dene." },
  youLeftTitle: "Maçtan çıktın",
  youLeftText: "Cevapların sayılıyor ama bitirenlerin altında yer alıyorsun.",
  excludedTitle: "Maç sensiz başladı",
  excludedText: "Zamanında onaylamadın. Bir sonraki için odada bekle.",
  gateTitle: "Herkesin katılması bekleniyor…",
  gateReady: "Hazır",
  gateWaiting: "Katılıyor…",
  connecting: "Bağlanıyor…",
  retry: "Tekrar dene",
  finishedTitle: "Maç bitti",
  finishedText: "Bu maç zaten bitti.",
};

const COPY: Record<Locale, Copy> = { es, en, ka, tr };
export const aproximadoCopy = (locale: string): Copy => COPY[(locale in COPY ? locale : "en") as Locale];
export type AproximadoCopy = Copy;

const NUMBER_LOCALE: Record<Locale, string> = { es: "es-AR", en: "en-GB", ka: "ka-GE", tr: "tr-TR" };
/** "85,5 M€", "74.500 espectadores": the number in the reader's locale with the question's unit. */
/** es/en pool units take a singular after exactly 1 ("a 1 gol"); ka and tr keep the singular after any number. */
const SINGULAR_UNIT: Record<string, string> = {
  goles: "gol", partidos: "partido", espectadores: "espectador", años: "año", socios: "socio",
  goals: "goal", games: "game", spectators: "spectator", years: "year", fans: "fan", members: "member",
};

export function formatValue(value: number, unit: string, precision: number, locale: string): string {
  const n = new Intl.NumberFormat(NUMBER_LOCALE[(locale in NUMBER_LOCALE ? locale : "en") as Locale], { maximumFractionDigits: precision, minimumFractionDigits: 0 }).format(value);
  const shown = Number(value.toFixed(precision)) === 1 && SINGULAR_UNIT[unit] ? SINGULAR_UNIT[unit] : unit;
  return shown ? `${n} ${shown}` : n;
}
