// GENERATED by scripts/gen-squad-spin-sample.py from the staging Squad Spin content — fixed combos
// for the sneak peek with their reels, valid answers and reviewed aliases. Regenerate rather than editing by hand.
import type { SampleSquadSpinCombo } from "../types";

export const SAMPLE_SQUAD_SPIN_COMBOS: SampleSquadSpinCombo[] = [
  {
    "id": "dfeed32b-abde-44fd-9ab9-1cd853e68b61",
    "tier": "t3e",
    "reels": [
      {
        "id": "51a790ab-f611-42d4-bd9d-878a59c1f956",
        "family": "club",
        "key": "club:bayer-04-leverkusen",
        "label_en": "Bayer 04 Leverkusen",
        "label_ka": "Bayer 04 Leverkusen",
        "asset_key": "bayer-04-leverkusen"
      },
      {
        "family": "position",
        "id": "DEF",
        "key": "DEF",
        "label_en": "Defender",
        "label_ka": "მცველი",
        "asset_key": null
      },
      {
        "id": "a1425bcb-8faf-4064-8482-ae01e8c84c7c",
        "family": "country",
        "key": "country:es",
        "label_en": "Spain",
        "label_ka": "ესპანეთი",
        "asset_key": "es"
      }
    ],
    "answers": [
      {
        "id": "7a947640-80de-4f6a-bb57-e7752909b74a",
        "name_en": "Mario Hermoso",
        "name_ka": "მარიო ერმოსო",
        "image_url": null
      },
      {
        "id": "a9a05114-da56-4d9f-adcc-d653b8582142",
        "name_en": "Alejandro Grimaldo",
        "name_ka": "ალეხანდრო გრიმალდო",
        "image_url": null
      },
      {
        "id": "b0cb2d4c-8a7b-4f49-955a-b5f904bf9685",
        "name_en": "Lucas Vázquez",
        "name_ka": "ლუკას ვასკესი",
        "image_url": null
      },
      {
        "id": "de28216d-257f-48ea-8292-46303b11e00d",
        "name_en": "Daniel Carvajal",
        "name_ka": "დანიელ კარვახალი",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "a9a05114-da56-4d9f-adcc-d653b8582142",
        "alias": "alejandro grimaldo",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "de28216d-257f-48ea-8292-46303b11e00d",
        "alias": "carvajal",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "de28216d-257f-48ea-8292-46303b11e00d",
        "alias": "carvajal daniel",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "de28216d-257f-48ea-8292-46303b11e00d",
        "alias": "daniel carvajal",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "a9a05114-da56-4d9f-adcc-d653b8582142",
        "alias": "grimaldo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "a9a05114-da56-4d9f-adcc-d653b8582142",
        "alias": "grimaldo alejandro",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "7a947640-80de-4f6a-bb57-e7752909b74a",
        "alias": "hermoso",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "7a947640-80de-4f6a-bb57-e7752909b74a",
        "alias": "hermoso mario",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "b0cb2d4c-8a7b-4f49-955a-b5f904bf9685",
        "alias": "lucas vazquez",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "7a947640-80de-4f6a-bb57-e7752909b74a",
        "alias": "mario hermoso",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "b0cb2d4c-8a7b-4f49-955a-b5f904bf9685",
        "alias": "vazquez lucas",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "a9a05114-da56-4d9f-adcc-d653b8582142",
        "alias": "ალეხანდრო გრიმალდო",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "de28216d-257f-48ea-8292-46303b11e00d",
        "alias": "დანიელ კარვახალი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "b0cb2d4c-8a7b-4f49-955a-b5f904bf9685",
        "alias": "ლუკას ვასკესი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "7a947640-80de-4f6a-bb57-e7752909b74a",
        "alias": "მარიო ერმოსო",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "a7142493-44b6-44f4-bf87-83c30fb2f2d2",
    "tier": "t3e",
    "reels": [
      {
        "id": "d706ce25-c978-4e11-bc36-d1093778849f",
        "family": "club",
        "key": "club:wl-malaga",
        "label_en": "Málaga",
        "label_ka": "Málaga",
        "asset_key": "wl-malaga"
      },
      {
        "family": "position",
        "id": "MID",
        "key": "MID",
        "label_en": "Midfielder",
        "label_ka": "ნახევარმცველი",
        "asset_key": null
      },
      {
        "id": "a1425bcb-8faf-4064-8482-ae01e8c84c7c",
        "family": "country",
        "key": "country:es",
        "label_en": "Spain",
        "label_ka": "ესპანეთი",
        "asset_key": "es"
      }
    ],
    "answers": [
      {
        "id": "5c38d987-e66c-4c70-ad79-5b1169591b0e",
        "name_en": "Pablo Fornals",
        "name_ka": "პაბლო ფორნალსი",
        "image_url": null
      },
      {
        "id": "9b56d51b-1b88-4add-9c5f-1a077606d5cc",
        "name_en": "Isco",
        "name_ka": "ისკო",
        "image_url": null
      },
      {
        "id": "a75e82c1-0f44-4c9a-8b62-d8315cfb84f2",
        "name_en": "Sergi Darder",
        "name_ka": "სერჟი დარდერი",
        "image_url": null
      },
      {
        "id": "d82f5b75-0360-4717-8439-1d3ff13d57da",
        "name_en": "Luis Alberto",
        "name_ka": "ლუის ალბერტო",
        "image_url": null
      },
      {
        "id": "ee5d3945-8c4b-4c8d-8001-bf0105c6eb65",
        "name_en": "Ignacio Camacho",
        "name_ka": "იგნასიო კამაჩო",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "d82f5b75-0360-4717-8439-1d3ff13d57da",
        "alias": "alberto luis",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "ee5d3945-8c4b-4c8d-8001-bf0105c6eb65",
        "alias": "camacho",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "ee5d3945-8c4b-4c8d-8001-bf0105c6eb65",
        "alias": "camacho ignacio",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "a75e82c1-0f44-4c9a-8b62-d8315cfb84f2",
        "alias": "darder",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "a75e82c1-0f44-4c9a-8b62-d8315cfb84f2",
        "alias": "darder sergi",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "5c38d987-e66c-4c70-ad79-5b1169591b0e",
        "alias": "fornals",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "5c38d987-e66c-4c70-ad79-5b1169591b0e",
        "alias": "fornals pablo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "9b56d51b-1b88-4add-9c5f-1a077606d5cc",
        "alias": "francisco alarcon",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "ee5d3945-8c4b-4c8d-8001-bf0105c6eb65",
        "alias": "ignacio camacho",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "9b56d51b-1b88-4add-9c5f-1a077606d5cc",
        "alias": "isco",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "9b56d51b-1b88-4add-9c5f-1a077606d5cc",
        "alias": "isco alarcon",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "d82f5b75-0360-4717-8439-1d3ff13d57da",
        "alias": "luis alberto",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "5c38d987-e66c-4c70-ad79-5b1169591b0e",
        "alias": "pablo fornals",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "a75e82c1-0f44-4c9a-8b62-d8315cfb84f2",
        "alias": "sergi darder",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "ee5d3945-8c4b-4c8d-8001-bf0105c6eb65",
        "alias": "იგნასიო კამაჩო",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "9b56d51b-1b88-4add-9c5f-1a077606d5cc",
        "alias": "ისკო",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "d82f5b75-0360-4717-8439-1d3ff13d57da",
        "alias": "ლუის ალბერტო",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "5c38d987-e66c-4c70-ad79-5b1169591b0e",
        "alias": "პაბლო ფორნალსი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "a75e82c1-0f44-4c9a-8b62-d8315cfb84f2",
        "alias": "სერჟი დარდერი",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "60fe3d22-47be-43dc-98bd-a7f175d5cd6d",
    "tier": "t3e",
    "reels": [
      {
        "id": "c968b162-abe1-4a39-9a1d-5a8596e2fc47",
        "family": "club",
        "key": "club:valencia-cf",
        "label_en": "Valencia CF",
        "label_ka": "Valencia CF",
        "asset_key": "valencia-cf"
      },
      {
        "family": "position",
        "id": "DEF",
        "key": "DEF",
        "label_en": "Defender",
        "label_ka": "მცველი",
        "asset_key": null
      },
      {
        "id": "9ff9403f-4645-4bcd-a6e6-984ecae19d0d",
        "family": "country",
        "key": "country:pt",
        "label_en": "Portugal",
        "label_ka": "პორტუგალია",
        "asset_key": "pt"
      }
    ],
    "answers": [
      {
        "id": "5471a5f5-a0b5-485d-9ed7-f349e80d2164",
        "name_en": "João Pereira",
        "name_ka": "ჟოაო პერეირა",
        "image_url": null
      },
      {
        "id": "73302f11-81c2-4e28-a4fe-57a2bfef3c14",
        "name_en": "Ferro",
        "name_ka": "ფერო",
        "image_url": null
      },
      {
        "id": "97e2b56a-99c2-4e19-9aad-5012106166a9",
        "name_en": "Thierry Correia",
        "name_ka": "ტიერი კორეია",
        "image_url": null
      },
      {
        "id": "d70a6fdb-c889-4f4b-98cd-13ce639e326f",
        "name_en": "João Cancelo",
        "name_ka": "ჟოაუ კანსელუ",
        "image_url": null
      },
      {
        "id": "e5eb6f47-e6b8-4ce8-b8e9-03b79ab6b00f",
        "name_en": "Rúben Vezo",
        "name_ka": "რუბენ ვეზუ",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "d70a6fdb-c889-4f4b-98cd-13ce639e326f",
        "alias": "cancelo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "d70a6fdb-c889-4f4b-98cd-13ce639e326f",
        "alias": "cancelo joao",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "97e2b56a-99c2-4e19-9aad-5012106166a9",
        "alias": "correia thierry",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "73302f11-81c2-4e28-a4fe-57a2bfef3c14",
        "alias": "ferro",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "d70a6fdb-c889-4f4b-98cd-13ce639e326f",
        "alias": "joao cancelo",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "5471a5f5-a0b5-485d-9ed7-f349e80d2164",
        "alias": "joao pereira",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "5471a5f5-a0b5-485d-9ed7-f349e80d2164",
        "alias": "pereira joao",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "e5eb6f47-e6b8-4ce8-b8e9-03b79ab6b00f",
        "alias": "ruben vezo",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "97e2b56a-99c2-4e19-9aad-5012106166a9",
        "alias": "thierry correia",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "e5eb6f47-e6b8-4ce8-b8e9-03b79ab6b00f",
        "alias": "vezo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "e5eb6f47-e6b8-4ce8-b8e9-03b79ab6b00f",
        "alias": "vezo ruben",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "5471a5f5-a0b5-485d-9ed7-f349e80d2164",
        "alias": "ჟოაო პერეირა",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "d70a6fdb-c889-4f4b-98cd-13ce639e326f",
        "alias": "ჟოაუ კანსელუ",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "e5eb6f47-e6b8-4ce8-b8e9-03b79ab6b00f",
        "alias": "რუბენ ვეზუ",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "97e2b56a-99c2-4e19-9aad-5012106166a9",
        "alias": "ტიერი კორეია",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "73302f11-81c2-4e28-a4fe-57a2bfef3c14",
        "alias": "ფერო",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "abbdac75-99fb-49e5-8581-aa37d9c144c0",
    "tier": "t3e",
    "reels": [
      {
        "id": "e311824e-bf90-4d89-b65d-4954e178a0dd",
        "family": "club",
        "key": "club:wl-monza",
        "label_en": "Monza",
        "label_ka": "Monza",
        "asset_key": "wl-monza"
      },
      {
        "family": "position",
        "id": "GK",
        "key": "GK",
        "label_en": "Goalkeeper",
        "label_ka": "მეკარე",
        "asset_key": null
      },
      {
        "id": "d9fcd591-5a46-443e-9ae0-9243e7140b81",
        "family": "country",
        "key": "country:it",
        "label_en": "Italy",
        "label_ka": "იტალია",
        "asset_key": "it"
      }
    ],
    "answers": [
      {
        "id": "6bd228d8-aa19-4553-b9dd-ddd8ee57103a",
        "name_en": "Stefano Turati",
        "name_ka": "სტეფანო ტურატი",
        "image_url": null
      },
      {
        "id": "99e8ea92-26b3-40a0-a80d-65b62564d8a7",
        "name_en": "Michele Di Gregorio",
        "name_ka": "მიკელე დი გრეგორიო",
        "image_url": null
      },
      {
        "id": "f7269e71-0834-414b-8a72-1b2bd4c28e6d",
        "name_en": "Alessio Cragno",
        "name_ka": "ალესიო კრანიო",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "f7269e71-0834-414b-8a72-1b2bd4c28e6d",
        "alias": "alessio cragno",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "f7269e71-0834-414b-8a72-1b2bd4c28e6d",
        "alias": "cragno",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "f7269e71-0834-414b-8a72-1b2bd4c28e6d",
        "alias": "cragno alessio",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "99e8ea92-26b3-40a0-a80d-65b62564d8a7",
        "alias": "gregorio",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "99e8ea92-26b3-40a0-a80d-65b62564d8a7",
        "alias": "gregorio michele di",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "99e8ea92-26b3-40a0-a80d-65b62564d8a7",
        "alias": "michele di gregorio",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "6bd228d8-aa19-4553-b9dd-ddd8ee57103a",
        "alias": "stefano turati",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "6bd228d8-aa19-4553-b9dd-ddd8ee57103a",
        "alias": "turati",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "6bd228d8-aa19-4553-b9dd-ddd8ee57103a",
        "alias": "turati stefano",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "f7269e71-0834-414b-8a72-1b2bd4c28e6d",
        "alias": "ალესიო კრანიო",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "99e8ea92-26b3-40a0-a80d-65b62564d8a7",
        "alias": "მიკელე დი გრეგორიო",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "6bd228d8-aa19-4553-b9dd-ddd8ee57103a",
        "alias": "სტეფანო ტურატი",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "db37f01c-33b6-45dc-b939-a9dda4967dfd",
    "tier": "t3e",
    "reels": [
      {
        "id": "44102a16-791c-439f-989f-805665d3f063",
        "family": "club",
        "key": "club:wl-rayo-vallecano",
        "label_en": "Rayo Vallecano",
        "label_ka": "Rayo Vallecano",
        "asset_key": "wl-rayo-vallecano"
      },
      {
        "family": "position",
        "id": "MID",
        "key": "MID",
        "label_en": "Midfielder",
        "label_ka": "ნახევარმცველი",
        "asset_key": null
      },
      {
        "id": "a1425bcb-8faf-4064-8482-ae01e8c84c7c",
        "family": "country",
        "key": "country:es",
        "label_en": "Spain",
        "label_ka": "ესპანეთი",
        "asset_key": "es"
      }
    ],
    "answers": [
      {
        "id": "1382a9a6-be30-4983-90f3-95c142367efd",
        "name_en": "Unai López",
        "name_ka": "უნაი ლოპესი",
        "image_url": null
      },
      {
        "id": "5610d0a7-4522-4cc3-ae6e-4c4aad8b9c7c",
        "name_en": "Santi Comesaña",
        "name_ka": "სანტი კომესანია",
        "image_url": null
      },
      {
        "id": "bed4eba7-db84-4357-9329-bea33c669e82",
        "name_en": "Javi Fuego",
        "name_ka": "ხავი ფუეგო",
        "image_url": null
      },
      {
        "id": "ca49c152-b02b-435f-b5df-454fac02347a",
        "name_en": "Saúl Ñíguez",
        "name_ka": "საულ ნიგესი",
        "image_url": null
      },
      {
        "id": "d26018c9-3501-459a-8fcc-2f728a4b7ffd",
        "name_en": "Pablo Hernández",
        "name_ka": "პაბლო ერნანდესი",
        "image_url": null
      },
      {
        "id": "e6862dbf-22a0-40cf-994d-0b6e3a638be5",
        "name_en": "Alejandro Pozuelo",
        "name_ka": "ალეხანდრო პოსუელო",
        "image_url": null
      },
      {
        "id": "f986b890-9121-4569-9a73-d9dd13f54dd8",
        "name_en": "Jonathan Viera",
        "name_ka": "ჯონათან ვიერა",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "e6862dbf-22a0-40cf-994d-0b6e3a638be5",
        "alias": "alejandro pozuelo",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "5610d0a7-4522-4cc3-ae6e-4c4aad8b9c7c",
        "alias": "comesana",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "5610d0a7-4522-4cc3-ae6e-4c4aad8b9c7c",
        "alias": "comesana santi",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "bed4eba7-db84-4357-9329-bea33c669e82",
        "alias": "fuego",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "bed4eba7-db84-4357-9329-bea33c669e82",
        "alias": "fuego javi",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "d26018c9-3501-459a-8fcc-2f728a4b7ffd",
        "alias": "hernandez pablo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "bed4eba7-db84-4357-9329-bea33c669e82",
        "alias": "javi fuego",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "f986b890-9121-4569-9a73-d9dd13f54dd8",
        "alias": "jonathan viera",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "1382a9a6-be30-4983-90f3-95c142367efd",
        "alias": "lopez unai",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "ca49c152-b02b-435f-b5df-454fac02347a",
        "alias": "niguez",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "ca49c152-b02b-435f-b5df-454fac02347a",
        "alias": "niguez saul",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "d26018c9-3501-459a-8fcc-2f728a4b7ffd",
        "alias": "pablo hernandez",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "e6862dbf-22a0-40cf-994d-0b6e3a638be5",
        "alias": "pozuelo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "e6862dbf-22a0-40cf-994d-0b6e3a638be5",
        "alias": "pozuelo alejandro",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "5610d0a7-4522-4cc3-ae6e-4c4aad8b9c7c",
        "alias": "santi comesana",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "ca49c152-b02b-435f-b5df-454fac02347a",
        "alias": "saul niguez",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "1382a9a6-be30-4983-90f3-95c142367efd",
        "alias": "unai lopez",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "f986b890-9121-4569-9a73-d9dd13f54dd8",
        "alias": "viera jonathan",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "e6862dbf-22a0-40cf-994d-0b6e3a638be5",
        "alias": "ალეხანდრო პოსუელო",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "d26018c9-3501-459a-8fcc-2f728a4b7ffd",
        "alias": "პაბლო ერნანდესი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "5610d0a7-4522-4cc3-ae6e-4c4aad8b9c7c",
        "alias": "სანტი კომესანია",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "ca49c152-b02b-435f-b5df-454fac02347a",
        "alias": "საულ ნიგესი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "1382a9a6-be30-4983-90f3-95c142367efd",
        "alias": "უნაი ლოპესი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "bed4eba7-db84-4357-9329-bea33c669e82",
        "alias": "ხავი ფუეგო",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "f986b890-9121-4569-9a73-d9dd13f54dd8",
        "alias": "ჯონათან ვიერა",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "c70a028c-0418-41f8-9a31-502f8781b1c0",
    "tier": "t3e",
    "reels": [
      {
        "id": "25115bec-9c3b-4cd8-9bbf-e0e63132b2bf",
        "family": "club",
        "key": "club:chelsea",
        "label_en": "Chelsea",
        "label_ka": "Chelsea",
        "asset_key": "chelsea"
      },
      {
        "family": "position",
        "id": "FWD",
        "key": "FWD",
        "label_en": "Forward",
        "label_ka": "თავდამსხმელი",
        "asset_key": null
      },
      {
        "id": "e64a784c-8b56-45ba-bdf7-7815d6539dda",
        "family": "country",
        "key": "country:gb-eng",
        "label_en": "England",
        "label_ka": "ინგლისი",
        "asset_key": "gb-eng"
      }
    ],
    "answers": [
      {
        "id": "01312c6d-a794-42a4-836a-88f97563fd71",
        "name_en": "Tyrique George",
        "name_ka": "ტაირიკ ჯორჯი",
        "image_url": null
      },
      {
        "id": "105c2d1a-69a2-47f1-982c-03131859288e",
        "name_en": "Noni Madueke",
        "name_ka": "ნონი მადუეკე",
        "image_url": null
      },
      {
        "id": "1950a150-8ce6-4b0d-aa91-92161bef4766",
        "name_en": "Dominic Solanke",
        "name_ka": "დომინიკ სოლანკე",
        "image_url": null
      },
      {
        "id": "5092c161-0d14-43e0-9ad9-08043b6ddf41",
        "name_en": "Callum Hudson-Odoi",
        "name_ka": "კალუმ ჰადსონ-ოდოი",
        "image_url": null
      },
      {
        "id": "51e1ae96-5a05-4387-acd7-eeafc62786e2",
        "name_en": "Tammy Abraham",
        "name_ka": "ტემი აბრაჰამი",
        "image_url": null
      },
      {
        "id": "56b38697-46e0-457c-bbbb-72604fb5dba3",
        "name_en": "Daniel Sturridge",
        "name_ka": "დანიელ სტარიჯი",
        "image_url": null
      },
      {
        "id": "76d92011-8582-40a6-9655-d69e41b50705",
        "name_en": "Jamie Gittens",
        "name_ka": "ჯეიმი გიტენსი",
        "image_url": null
      },
      {
        "id": "792f1313-70e6-45a4-9079-71321a16848d",
        "name_en": "Jadon Sancho",
        "name_ka": "ჯეიდონ სანჩო",
        "image_url": null
      },
      {
        "id": "bec36cad-dbad-4f54-ac17-8749362ae474",
        "name_en": "Raheem Sterling",
        "name_ka": "რაჰიმ სტერლინგი",
        "image_url": null
      },
      {
        "id": "e68b2cf8-d41f-40b5-a550-0b892f66b1e7",
        "name_en": "Liam Delap",
        "name_ka": "ლიამ დელაპი",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "51e1ae96-5a05-4387-acd7-eeafc62786e2",
        "alias": "abraham",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "51e1ae96-5a05-4387-acd7-eeafc62786e2",
        "alias": "abraham tammy",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "5092c161-0d14-43e0-9ad9-08043b6ddf41",
        "alias": "callum hudson odoi",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "56b38697-46e0-457c-bbbb-72604fb5dba3",
        "alias": "dan sturridge",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "56b38697-46e0-457c-bbbb-72604fb5dba3",
        "alias": "daniel sturige",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "56b38697-46e0-457c-bbbb-72604fb5dba3",
        "alias": "daniel sturridge",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "e68b2cf8-d41f-40b5-a550-0b892f66b1e7",
        "alias": "delap",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "e68b2cf8-d41f-40b5-a550-0b892f66b1e7",
        "alias": "delap liam",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "1950a150-8ce6-4b0d-aa91-92161bef4766",
        "alias": "dominic solanke",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "01312c6d-a794-42a4-836a-88f97563fd71",
        "alias": "george tyrique",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "76d92011-8582-40a6-9655-d69e41b50705",
        "alias": "gittens",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "76d92011-8582-40a6-9655-d69e41b50705",
        "alias": "gittens jamie",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "5092c161-0d14-43e0-9ad9-08043b6ddf41",
        "alias": "hudson odoi",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "5092c161-0d14-43e0-9ad9-08043b6ddf41",
        "alias": "hudson odoi callum",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "792f1313-70e6-45a4-9079-71321a16848d",
        "alias": "jadon",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "792f1313-70e6-45a4-9079-71321a16848d",
        "alias": "jadon sancho",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "76d92011-8582-40a6-9655-d69e41b50705",
        "alias": "jamie gittens",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "e68b2cf8-d41f-40b5-a550-0b892f66b1e7",
        "alias": "liam",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "e68b2cf8-d41f-40b5-a550-0b892f66b1e7",
        "alias": "liam delap",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "105c2d1a-69a2-47f1-982c-03131859288e",
        "alias": "madueke",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "105c2d1a-69a2-47f1-982c-03131859288e",
        "alias": "madueke noni",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "105c2d1a-69a2-47f1-982c-03131859288e",
        "alias": "noni",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "105c2d1a-69a2-47f1-982c-03131859288e",
        "alias": "noni madueke",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "bec36cad-dbad-4f54-ac17-8749362ae474",
        "alias": "raheem",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "bec36cad-dbad-4f54-ac17-8749362ae474",
        "alias": "raheem steling",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "bec36cad-dbad-4f54-ac17-8749362ae474",
        "alias": "raheem sterling",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "bec36cad-dbad-4f54-ac17-8749362ae474",
        "alias": "rahim sterling",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "792f1313-70e6-45a4-9079-71321a16848d",
        "alias": "sancho",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "792f1313-70e6-45a4-9079-71321a16848d",
        "alias": "sancho jadon",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "1950a150-8ce6-4b0d-aa91-92161bef4766",
        "alias": "solanke",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "1950a150-8ce6-4b0d-aa91-92161bef4766",
        "alias": "solanke dominic",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "bec36cad-dbad-4f54-ac17-8749362ae474",
        "alias": "sterling",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "bec36cad-dbad-4f54-ac17-8749362ae474",
        "alias": "sterling raheem",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "56b38697-46e0-457c-bbbb-72604fb5dba3",
        "alias": "sturridge",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "56b38697-46e0-457c-bbbb-72604fb5dba3",
        "alias": "sturridge daniel",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "51e1ae96-5a05-4387-acd7-eeafc62786e2",
        "alias": "tammy",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "51e1ae96-5a05-4387-acd7-eeafc62786e2",
        "alias": "tammy abraham",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "01312c6d-a794-42a4-836a-88f97563fd71",
        "alias": "tyrique",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "01312c6d-a794-42a4-836a-88f97563fd71",
        "alias": "tyrique george",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "56b38697-46e0-457c-bbbb-72604fb5dba3",
        "alias": "დანიელ სტარიჯი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "1950a150-8ce6-4b0d-aa91-92161bef4766",
        "alias": "დომინიკ სოლანკე",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "5092c161-0d14-43e0-9ad9-08043b6ddf41",
        "alias": "კალუმ ჰადსონ ოდოი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "e68b2cf8-d41f-40b5-a550-0b892f66b1e7",
        "alias": "ლიამ დელაპი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "105c2d1a-69a2-47f1-982c-03131859288e",
        "alias": "ნონი მადუეკე",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "bec36cad-dbad-4f54-ac17-8749362ae474",
        "alias": "რაჰიმ სტერლინგი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "1950a150-8ce6-4b0d-aa91-92161bef4766",
        "alias": "სოლანკე",
        "locale": "ka",
        "policy": "unique_only"
      },
      {
        "player_id": "01312c6d-a794-42a4-836a-88f97563fd71",
        "alias": "ტაირიკ ჯორჯი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "51e1ae96-5a05-4387-acd7-eeafc62786e2",
        "alias": "ტემი აბრაჰამი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "792f1313-70e6-45a4-9079-71321a16848d",
        "alias": "ჯეიდონ სანჩო",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "76d92011-8582-40a6-9655-d69e41b50705",
        "alias": "ჯეიმი გიტენსი",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "86e9968a-f684-44b5-bb37-16b5475df71b",
    "tier": "t3e",
    "reels": [
      {
        "id": "25115bec-9c3b-4cd8-9bbf-e0e63132b2bf",
        "family": "club",
        "key": "club:chelsea",
        "label_en": "Chelsea",
        "label_ka": "Chelsea",
        "asset_key": "chelsea"
      },
      {
        "family": "position",
        "id": "MID",
        "key": "MID",
        "label_en": "Midfielder",
        "label_ka": "ნახევარმცველი",
        "asset_key": null
      },
      {
        "id": "7877c49f-628b-4207-81e9-2baca4016a26",
        "family": "country",
        "key": "country:ar",
        "label_en": "Argentina",
        "label_ka": "არგენტინა",
        "asset_key": "ar"
      }
    ],
    "answers": [
      {
        "id": "2ee2187f-a8e4-4f73-b670-11586e0b5661",
        "name_en": "Facundo Buonanotte",
        "name_ka": "ფაკუნდო ბუონანოტე",
        "image_url": null
      },
      {
        "id": "b0550e07-c6a5-4bbb-a095-d336f0d3c0f0",
        "name_en": "Enzo Fernández",
        "name_ka": "ენცო ფერნანდესი",
        "image_url": null
      },
      {
        "id": "d0a233f5-36ae-4187-ba49-73fe1da1e23e",
        "name_en": "Juan Sebastián Verón",
        "name_ka": "ხუან სებასტიან ვერონი",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "2ee2187f-a8e4-4f73-b670-11586e0b5661",
        "alias": "buonanotte",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "2ee2187f-a8e4-4f73-b670-11586e0b5661",
        "alias": "buonanotte facundo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "b0550e07-c6a5-4bbb-a095-d336f0d3c0f0",
        "alias": "enzo fernandez",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "2ee2187f-a8e4-4f73-b670-11586e0b5661",
        "alias": "facundo buonanotte",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "b0550e07-c6a5-4bbb-a095-d336f0d3c0f0",
        "alias": "fernandez enzo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "d0a233f5-36ae-4187-ba49-73fe1da1e23e",
        "alias": "j veron",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "d0a233f5-36ae-4187-ba49-73fe1da1e23e",
        "alias": "juan sebastian veron",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "d0a233f5-36ae-4187-ba49-73fe1da1e23e",
        "alias": "la brujita",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "d0a233f5-36ae-4187-ba49-73fe1da1e23e",
        "alias": "veron juan sebastian",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "b0550e07-c6a5-4bbb-a095-d336f0d3c0f0",
        "alias": "ენცო ფერნანდესი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "2ee2187f-a8e4-4f73-b670-11586e0b5661",
        "alias": "ფაკუნდო ბუონანოტე",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "d0a233f5-36ae-4187-ba49-73fe1da1e23e",
        "alias": "ხუან სებასტიან ვერონი",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "37d5358b-6940-4458-a79a-c12b183afa8f",
    "tier": "t3e",
    "reels": [
      {
        "id": "34eca891-aee8-4a0b-8e03-dcae77a66519",
        "family": "club",
        "key": "club:sevilla-fc",
        "label_en": "Sevilla FC",
        "label_ka": "Sevilla FC",
        "asset_key": "sevilla-fc"
      },
      {
        "family": "position",
        "id": "FWD",
        "key": "FWD",
        "label_en": "Forward",
        "label_ka": "თავდამსხმელი",
        "asset_key": null
      },
      {
        "id": "7877c49f-628b-4207-81e9-2baca4016a26",
        "family": "country",
        "key": "country:ar",
        "label_en": "Argentina",
        "label_ka": "არგენტინა",
        "asset_key": "ar"
      }
    ],
    "answers": [
      {
        "id": "145e057f-e280-48df-9b04-83cb5cd042ad",
        "name_en": "Diego Perotti",
        "name_ka": "დიეგო პეროტი",
        "image_url": null
      },
      {
        "id": "2143632c-db0c-435a-aabe-8de6f632a4ea",
        "name_en": "Luciano Vietto",
        "name_ka": "ლუჩიანო ვიეტო",
        "image_url": null
      },
      {
        "id": "450d1c73-244d-45e9-87b7-b34a19f701a3",
        "name_en": "Alejo Veliz",
        "name_ka": "ალეხო ველისი",
        "image_url": null
      },
      {
        "id": "65177212-1844-4330-aa90-d6c99340ede4",
        "name_en": "Lucas Ocampos",
        "name_ka": "ლუკას ოკამპოსი",
        "image_url": null
      },
      {
        "id": "c3c8ff15-cad2-409e-816c-b95a72c0eb9c",
        "name_en": "Erik Lamela",
        "name_ka": "ერიკ ლამელა",
        "image_url": null
      },
      {
        "id": "fc39f30b-a21f-469b-be69-7a7ebacc7c33",
        "name_en": "Joaquín Correa",
        "name_ka": "ხოაკინ კორეა",
        "image_url": null
      },
      {
        "id": "fc9f257b-0405-43fb-b97a-947e0522305b",
        "name_en": "Papu Gómez",
        "name_ka": "პაპუ გომესი",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "450d1c73-244d-45e9-87b7-b34a19f701a3",
        "alias": "alejo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "450d1c73-244d-45e9-87b7-b34a19f701a3",
        "alias": "alejo veliz",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "fc39f30b-a21f-469b-be69-7a7ebacc7c33",
        "alias": "correa joaquin",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "145e057f-e280-48df-9b04-83cb5cd042ad",
        "alias": "diego perotti",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "c3c8ff15-cad2-409e-816c-b95a72c0eb9c",
        "alias": "erik lamela",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "fc9f257b-0405-43fb-b97a-947e0522305b",
        "alias": "gomez papu",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "fc39f30b-a21f-469b-be69-7a7ebacc7c33",
        "alias": "joaquin correa",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "c3c8ff15-cad2-409e-816c-b95a72c0eb9c",
        "alias": "lamela",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "c3c8ff15-cad2-409e-816c-b95a72c0eb9c",
        "alias": "lamela erik",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "65177212-1844-4330-aa90-d6c99340ede4",
        "alias": "lucas ocampos",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "2143632c-db0c-435a-aabe-8de6f632a4ea",
        "alias": "luciano vietto",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "65177212-1844-4330-aa90-d6c99340ede4",
        "alias": "ocampos",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "65177212-1844-4330-aa90-d6c99340ede4",
        "alias": "ocampos lucas",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "fc9f257b-0405-43fb-b97a-947e0522305b",
        "alias": "papu",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "fc9f257b-0405-43fb-b97a-947e0522305b",
        "alias": "papu gomez",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "145e057f-e280-48df-9b04-83cb5cd042ad",
        "alias": "perotti",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "145e057f-e280-48df-9b04-83cb5cd042ad",
        "alias": "perotti diego",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "450d1c73-244d-45e9-87b7-b34a19f701a3",
        "alias": "veliz",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "450d1c73-244d-45e9-87b7-b34a19f701a3",
        "alias": "veliz alejo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "2143632c-db0c-435a-aabe-8de6f632a4ea",
        "alias": "vietto",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "2143632c-db0c-435a-aabe-8de6f632a4ea",
        "alias": "vietto luciano",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "450d1c73-244d-45e9-87b7-b34a19f701a3",
        "alias": "ალეხო ველისი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "145e057f-e280-48df-9b04-83cb5cd042ad",
        "alias": "დიეგო პეროტი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "c3c8ff15-cad2-409e-816c-b95a72c0eb9c",
        "alias": "ერიკ ლამელა",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "65177212-1844-4330-aa90-d6c99340ede4",
        "alias": "ლუკას ოკამპოსი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "2143632c-db0c-435a-aabe-8de6f632a4ea",
        "alias": "ლუჩიანო ვიეტო",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "fc9f257b-0405-43fb-b97a-947e0522305b",
        "alias": "პაპუ გომესი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "fc39f30b-a21f-469b-be69-7a7ebacc7c33",
        "alias": "ხოაკინ კორეა",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "4d96656f-3e39-42b9-a5d3-932c00b9a91b",
    "tier": "t3e",
    "reels": [
      {
        "id": "3ba2f194-7076-41b1-9d92-278233f8247f",
        "family": "club",
        "key": "club:ac-milan",
        "label_en": "AC Milan",
        "label_ka": "AC Milan",
        "asset_key": "ac-milan"
      },
      {
        "family": "position",
        "id": "FWD",
        "key": "FWD",
        "label_en": "Forward",
        "label_ka": "თავდამსხმელი",
        "asset_key": null
      },
      {
        "id": "6d6f23c6-3ee4-42f1-87a3-faf78f37242e",
        "family": "country",
        "key": "country:hr",
        "label_en": "Croatia",
        "label_ka": "ხორვატია",
        "asset_key": "hr"
      }
    ],
    "answers": [
      {
        "id": "342bb29b-3466-44e9-abe5-b3fbcabd0693",
        "name_en": "Nikola Kalinic",
        "name_ka": "ნიკოლა კალინიჩი",
        "image_url": null
      },
      {
        "id": "6d26b2f2-ab25-4be2-900e-4a2d0302e884",
        "name_en": "Ante Rebić",
        "name_ka": "ანტე რებიჩი",
        "image_url": null
      },
      {
        "id": "afacf855-4426-4fca-b2fe-33afe829a562",
        "name_en": "Mario Mandzukic",
        "name_ka": "მარიო მანჯუკიჩი",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "6d26b2f2-ab25-4be2-900e-4a2d0302e884",
        "alias": "ante rebic",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "342bb29b-3466-44e9-abe5-b3fbcabd0693",
        "alias": "kalinic",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "342bb29b-3466-44e9-abe5-b3fbcabd0693",
        "alias": "kalinic nikola",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "afacf855-4426-4fca-b2fe-33afe829a562",
        "alias": "mandzuchic",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "afacf855-4426-4fca-b2fe-33afe829a562",
        "alias": "mandzukic",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "afacf855-4426-4fca-b2fe-33afe829a562",
        "alias": "mandzukic mario",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "afacf855-4426-4fca-b2fe-33afe829a562",
        "alias": "mandzunic",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "afacf855-4426-4fca-b2fe-33afe829a562",
        "alias": "mario mandzukic",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "342bb29b-3466-44e9-abe5-b3fbcabd0693",
        "alias": "nikola kalinic",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "6d26b2f2-ab25-4be2-900e-4a2d0302e884",
        "alias": "rebic",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "6d26b2f2-ab25-4be2-900e-4a2d0302e884",
        "alias": "rebic ante",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "6d26b2f2-ab25-4be2-900e-4a2d0302e884",
        "alias": "ანტე რებიჩი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "afacf855-4426-4fca-b2fe-33afe829a562",
        "alias": "მანჯუკიჩ",
        "locale": "ka",
        "policy": "unique_only"
      },
      {
        "player_id": "afacf855-4426-4fca-b2fe-33afe829a562",
        "alias": "მანჯუკიჩი",
        "locale": "ka",
        "policy": "unique_only"
      },
      {
        "player_id": "afacf855-4426-4fca-b2fe-33afe829a562",
        "alias": "მარიო მანჯუკიჩ",
        "locale": "ka",
        "policy": "unique_only"
      },
      {
        "player_id": "afacf855-4426-4fca-b2fe-33afe829a562",
        "alias": "მარიო მანჯუკიჩი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "342bb29b-3466-44e9-abe5-b3fbcabd0693",
        "alias": "ნიკოლა კალინიჩი",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "774e7242-5be3-4f78-b485-b96dd72b56dd",
    "tier": "t3e",
    "reels": [
      {
        "id": "b031040f-a2f1-49e7-9ee8-61352ec250be",
        "family": "club",
        "key": "club:liverpool",
        "label_en": "Liverpool",
        "label_ka": "Liverpool",
        "asset_key": "liverpool"
      },
      {
        "family": "position",
        "id": "FWD",
        "key": "FWD",
        "label_en": "Forward",
        "label_ka": "თავდამსხმელი",
        "asset_key": null
      },
      {
        "id": "a1425bcb-8faf-4064-8482-ae01e8c84c7c",
        "family": "country",
        "key": "country:es",
        "label_en": "Spain",
        "label_ka": "ესპანეთი",
        "asset_key": "es"
      }
    ],
    "answers": [
      {
        "id": "544122df-f446-4316-b16f-cde987e7b4d3",
        "name_en": "Fernando Morientes",
        "name_ka": "ფერნანდო მორიენტესი",
        "image_url": null
      },
      {
        "id": "6ac3cea7-1781-4eaa-9f70-6f535bda501a",
        "name_en": "Sergi Canós",
        "name_ka": "სერჟი კანოსი",
        "image_url": null
      },
      {
        "id": "97071d07-75c8-45ab-ac93-b3ebc7435729",
        "name_en": "Iago Aspas",
        "name_ka": "იაგო ასპასი",
        "image_url": null
      },
      {
        "id": "c9692588-f93b-4035-8737-8f625d1ec829",
        "name_en": "Fernando Torres",
        "name_ka": "ფერნანდო ტორესი",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "97071d07-75c8-45ab-ac93-b3ebc7435729",
        "alias": "aspas",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "97071d07-75c8-45ab-ac93-b3ebc7435729",
        "alias": "aspas iago",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "6ac3cea7-1781-4eaa-9f70-6f535bda501a",
        "alias": "canos",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "6ac3cea7-1781-4eaa-9f70-6f535bda501a",
        "alias": "canos sergi",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "c9692588-f93b-4035-8737-8f625d1ec829",
        "alias": "el nino",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "c9692588-f93b-4035-8737-8f625d1ec829",
        "alias": "el nino torres",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "544122df-f446-4316-b16f-cde987e7b4d3",
        "alias": "f morientes",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "c9692588-f93b-4035-8737-8f625d1ec829",
        "alias": "fernando jose torres",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "544122df-f446-4316-b16f-cde987e7b4d3",
        "alias": "fernando morientes",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "544122df-f446-4316-b16f-cde987e7b4d3",
        "alias": "fernando morientes sanchez",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "c9692588-f93b-4035-8737-8f625d1ec829",
        "alias": "fernando torres",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "97071d07-75c8-45ab-ac93-b3ebc7435729",
        "alias": "iago aspas",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "544122df-f446-4316-b16f-cde987e7b4d3",
        "alias": "morientes",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "544122df-f446-4316-b16f-cde987e7b4d3",
        "alias": "morientes fernando",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "6ac3cea7-1781-4eaa-9f70-6f535bda501a",
        "alias": "sergi canos",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "c9692588-f93b-4035-8737-8f625d1ec829",
        "alias": "torres fernando",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "97071d07-75c8-45ab-ac93-b3ebc7435729",
        "alias": "yago aspas",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "97071d07-75c8-45ab-ac93-b3ebc7435729",
        "alias": "იაგო ასპასი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "6ac3cea7-1781-4eaa-9f70-6f535bda501a",
        "alias": "სერჟი კანოსი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "544122df-f446-4316-b16f-cde987e7b4d3",
        "alias": "ფერნანდო მორიენტესი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "c9692588-f93b-4035-8737-8f625d1ec829",
        "alias": "ფერნანდო ტორესი",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "1935cd20-7a6c-4d56-8a7e-ac3aef527be6",
    "tier": "t3m",
    "reels": [
      {
        "id": "24b42841-8ab2-4525-9f61-69fb039c6949",
        "family": "club",
        "key": "club:villarreal-cf",
        "label_en": "Villarreal CF",
        "label_ka": "Villarreal CF",
        "asset_key": "villarreal-cf"
      },
      {
        "family": "position",
        "id": "FWD",
        "key": "FWD",
        "label_en": "Forward",
        "label_ka": "თავდამსხმელი",
        "asset_key": null
      },
      {
        "id": "f0e3273b-4f08-4822-b072-f390dfa816f3",
        "family": "country",
        "key": "country:cm",
        "label_en": "Cameroon",
        "label_ka": "კამერუნი",
        "asset_key": "cm"
      }
    ],
    "answers": [
      {
        "id": "1189b30a-e803-4d4e-b9a6-501e370d2e17",
        "name_en": "Karl Etta Eyong",
        "name_ka": "კარლ ეტა ეიონგი",
        "image_url": null
      },
      {
        "id": "bd61f9d5-d750-451a-95e0-461d53d26bf4",
        "name_en": "Karl Toko Ekambi",
        "name_ka": "კარლ ტოკო ეკამბი",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "bd61f9d5-d750-451a-95e0-461d53d26bf4",
        "alias": "ekambi",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "bd61f9d5-d750-451a-95e0-461d53d26bf4",
        "alias": "ekambi karl toko",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "1189b30a-e803-4d4e-b9a6-501e370d2e17",
        "alias": "eyong",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "1189b30a-e803-4d4e-b9a6-501e370d2e17",
        "alias": "eyong karl etta",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "1189b30a-e803-4d4e-b9a6-501e370d2e17",
        "alias": "karl etta eyong",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "bd61f9d5-d750-451a-95e0-461d53d26bf4",
        "alias": "karl toko ekambi",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "1189b30a-e803-4d4e-b9a6-501e370d2e17",
        "alias": "კარლ ეტა ეიონგი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "bd61f9d5-d750-451a-95e0-461d53d26bf4",
        "alias": "კარლ ტოკო ეკამბი",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "499c9da4-759b-4131-99e5-bca70124ca52",
    "tier": "t3m",
    "reels": [
      {
        "id": "495692f5-cc55-4283-bfdc-a870bc868288",
        "family": "club",
        "key": "club:as-monaco",
        "label_en": "AS Monaco",
        "label_ka": "AS Monaco",
        "asset_key": "as-monaco"
      },
      {
        "family": "position",
        "id": "MID",
        "key": "MID",
        "label_en": "Midfielder",
        "label_ka": "ნახევარმცველი",
        "asset_key": null
      },
      {
        "id": "81fa0e0e-55dd-46fc-80f7-6d862a44d730",
        "family": "country",
        "key": "country:be",
        "label_en": "Belgium",
        "label_ka": "ბელგია",
        "asset_key": "be"
      }
    ],
    "answers": [
      {
        "id": "ad52c4f6-3b41-41c6-8c33-e8e28adfa6b7",
        "name_en": "Eliot Matazo",
        "name_ka": "ელიოტ მატაზო",
        "image_url": null
      },
      {
        "id": "c56f9c35-9cef-4733-b80e-faad28b3c3b8",
        "name_en": "Youri Tielemans",
        "name_ka": "იური ტილემანსი",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "ad52c4f6-3b41-41c6-8c33-e8e28adfa6b7",
        "alias": "eliot",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "ad52c4f6-3b41-41c6-8c33-e8e28adfa6b7",
        "alias": "eliot matazo",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "ad52c4f6-3b41-41c6-8c33-e8e28adfa6b7",
        "alias": "matazo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "ad52c4f6-3b41-41c6-8c33-e8e28adfa6b7",
        "alias": "matazo eliot",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "c56f9c35-9cef-4733-b80e-faad28b3c3b8",
        "alias": "tielemans",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "c56f9c35-9cef-4733-b80e-faad28b3c3b8",
        "alias": "tielemans youri",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "c56f9c35-9cef-4733-b80e-faad28b3c3b8",
        "alias": "youri tielemans",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "ad52c4f6-3b41-41c6-8c33-e8e28adfa6b7",
        "alias": "ელიოტ მატაზო",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "c56f9c35-9cef-4733-b80e-faad28b3c3b8",
        "alias": "იურ",
        "locale": "ka",
        "policy": "unique_only"
      },
      {
        "player_id": "c56f9c35-9cef-4733-b80e-faad28b3c3b8",
        "alias": "იური",
        "locale": "ka",
        "policy": "unique_only"
      },
      {
        "player_id": "c56f9c35-9cef-4733-b80e-faad28b3c3b8",
        "alias": "იური ტილემანს",
        "locale": "ka",
        "policy": "unique_only"
      },
      {
        "player_id": "c56f9c35-9cef-4733-b80e-faad28b3c3b8",
        "alias": "იური ტილემანსი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "c56f9c35-9cef-4733-b80e-faad28b3c3b8",
        "alias": "ტილემანს",
        "locale": "ka",
        "policy": "unique_only"
      },
      {
        "player_id": "c56f9c35-9cef-4733-b80e-faad28b3c3b8",
        "alias": "ტილემანსი",
        "locale": "ka",
        "policy": "unique_only"
      }
    ]
  },
  {
    "id": "9638ac2f-95f9-47a2-8a13-347d70653e02",
    "tier": "t3m",
    "reels": [
      {
        "id": "034e0638-6d64-45c8-ba1e-7f9847c32cd4",
        "family": "club",
        "key": "club:wl-olympiacos",
        "label_en": "Olympiacos",
        "label_ka": "Olympiacos",
        "asset_key": "wl-olympiacos"
      },
      {
        "family": "position",
        "id": "MID",
        "key": "MID",
        "label_en": "Midfielder",
        "label_ka": "ნახევარმცველი",
        "asset_key": null
      },
      {
        "id": "1167f154-6b3e-46f4-bacd-f3d916069427",
        "family": "country",
        "key": "country:br",
        "label_en": "Brazil",
        "label_ka": "ბრაზილია",
        "asset_key": "br"
      }
    ],
    "answers": [
      {
        "id": "8eb86174-29f3-4034-99d5-7f9d39b5bdbb",
        "name_en": "Rivaldo",
        "name_ka": "რივალდო",
        "image_url": null
      },
      {
        "id": "cfe2c7ef-0233-4968-8ef2-90a8f1863855",
        "name_en": "Gustavo Scarpa",
        "name_ka": "გუსტავო სკარპა",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "cfe2c7ef-0233-4968-8ef2-90a8f1863855",
        "alias": "gustavo scarpa",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "8eb86174-29f3-4034-99d5-7f9d39b5bdbb",
        "alias": "rivaldo",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "cfe2c7ef-0233-4968-8ef2-90a8f1863855",
        "alias": "scarpa",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "cfe2c7ef-0233-4968-8ef2-90a8f1863855",
        "alias": "scarpa gustavo",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "cfe2c7ef-0233-4968-8ef2-90a8f1863855",
        "alias": "გუსტავო სკარპა",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "8eb86174-29f3-4034-99d5-7f9d39b5bdbb",
        "alias": "რივალდო",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "9d191c2e-6560-403b-a026-fefe4018e5fa",
    "tier": "t3m",
    "reels": [
      {
        "id": "338d033f-873d-4de5-8d5d-ed38690ed3f9",
        "family": "club",
        "key": "club:afc-ajax",
        "label_en": "AFC Ajax",
        "label_ka": "AFC Ajax",
        "asset_key": "afc-ajax"
      },
      {
        "family": "position",
        "id": "FWD",
        "key": "FWD",
        "label_en": "Forward",
        "label_ka": "თავდამსხმელი",
        "asset_key": null
      },
      {
        "id": "7877c49f-628b-4207-81e9-2baca4016a26",
        "family": "country",
        "key": "country:ar",
        "label_en": "Argentina",
        "label_ka": "არგენტინა",
        "asset_key": "ar"
      }
    ],
    "answers": [
      {
        "id": "65177212-1844-4330-aa90-d6c99340ede4",
        "name_en": "Lucas Ocampos",
        "name_ka": "ლუკას ოკამპოსი",
        "image_url": null
      },
      {
        "id": "7a6483ff-dc51-48d3-87a6-68bf6e297d30",
        "name_en": "Maher Carrizo",
        "name_ka": "მაჰერ კარისო",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "7a6483ff-dc51-48d3-87a6-68bf6e297d30",
        "alias": "carrizo maher",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "65177212-1844-4330-aa90-d6c99340ede4",
        "alias": "lucas ocampos",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "7a6483ff-dc51-48d3-87a6-68bf6e297d30",
        "alias": "maher carrizo",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "65177212-1844-4330-aa90-d6c99340ede4",
        "alias": "ocampos",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "65177212-1844-4330-aa90-d6c99340ede4",
        "alias": "ocampos lucas",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "65177212-1844-4330-aa90-d6c99340ede4",
        "alias": "ლუკას ოკამპოსი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "7a6483ff-dc51-48d3-87a6-68bf6e297d30",
        "alias": "მაჰერ კარისო",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "9d5b0a48-1a1d-4b59-855a-8627694f59a0",
    "tier": "t3m",
    "reels": [
      {
        "id": "4b52e720-6597-4b28-82be-c0f047e19104",
        "family": "club",
        "key": "club:wl-bournemouth",
        "label_en": "Bournemouth",
        "label_ka": "Bournemouth",
        "asset_key": "wl-bournemouth"
      },
      {
        "family": "position",
        "id": "FWD",
        "key": "FWD",
        "label_en": "Forward",
        "label_ka": "თავდამსხმელი",
        "asset_key": null
      },
      {
        "id": "6fec083d-ea42-4eed-bd49-0292b6be1129",
        "family": "country",
        "key": "country:gb-wls",
        "label_en": "Wales",
        "label_ka": "უელსი",
        "asset_key": "gb-wls"
      }
    ],
    "answers": [
      {
        "id": "32ab5d21-8dc2-431f-a9b1-914dd6a62230",
        "name_en": "Harry Wilson",
        "name_ka": "ჰარი უილსონი",
        "image_url": null
      },
      {
        "id": "bb8d0877-7907-47b9-a26d-b01355015f7e",
        "name_en": "David Brooks",
        "name_ka": "დევიდ ბრუკსი",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "bb8d0877-7907-47b9-a26d-b01355015f7e",
        "alias": "brooks david",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "bb8d0877-7907-47b9-a26d-b01355015f7e",
        "alias": "david brooks",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "32ab5d21-8dc2-431f-a9b1-914dd6a62230",
        "alias": "harry wilson",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "32ab5d21-8dc2-431f-a9b1-914dd6a62230",
        "alias": "wilson harry",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "bb8d0877-7907-47b9-a26d-b01355015f7e",
        "alias": "დევიდ ბრუკსი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "32ab5d21-8dc2-431f-a9b1-914dd6a62230",
        "alias": "ჰარი უილსონი",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  },
  {
    "id": "bebaa811-712f-402e-a809-77f0ab1e5157",
    "tier": "t3m",
    "reels": [
      {
        "id": "a5d62cf0-a3f3-4eba-a896-11666392466b",
        "family": "club",
        "key": "club:wl-queens-park-rangers",
        "label_en": "Queens Park Rangers",
        "label_ka": "Queens Park Rangers",
        "asset_key": "wl-queens-park-rangers"
      },
      {
        "family": "position",
        "id": "FWD",
        "key": "FWD",
        "label_en": "Forward",
        "label_ka": "თავდამსხმელი",
        "asset_key": null
      },
      {
        "id": "87e44cc5-0093-4aae-b80b-db00bc86cb41",
        "family": "country",
        "key": "country:fr",
        "label_en": "France",
        "label_ka": "საფრანგეთი",
        "asset_key": "fr"
      }
    ],
    "answers": [
      {
        "id": "04d5b66c-4a82-4a47-94ba-25349adba7a9",
        "name_en": "Djibril Cissé",
        "name_ka": "ჯიბრილ სისე",
        "image_url": null
      },
      {
        "id": "87898bb3-d021-47ee-b6a9-20e0dda5890b",
        "name_en": "Loïc Rémy",
        "name_ka": "ლოიკ რემი",
        "image_url": null
      }
    ],
    "aliases": [
      {
        "player_id": "04d5b66c-4a82-4a47-94ba-25349adba7a9",
        "alias": "cisse djibril",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "04d5b66c-4a82-4a47-94ba-25349adba7a9",
        "alias": "djibril cisse",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "87898bb3-d021-47ee-b6a9-20e0dda5890b",
        "alias": "loic remy",
        "locale": "en",
        "policy": "exact"
      },
      {
        "player_id": "87898bb3-d021-47ee-b6a9-20e0dda5890b",
        "alias": "remy loic",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "04d5b66c-4a82-4a47-94ba-25349adba7a9",
        "alias": "sisse",
        "locale": "en",
        "policy": "unique_only"
      },
      {
        "player_id": "87898bb3-d021-47ee-b6a9-20e0dda5890b",
        "alias": "ლოიკ რემი",
        "locale": "ka",
        "policy": "exact"
      },
      {
        "player_id": "04d5b66c-4a82-4a47-94ba-25349adba7a9",
        "alias": "ჯიბრილ სისე",
        "locale": "ka",
        "policy": "exact"
      }
    ]
  }
];
