import type { ClueKind, LocalizedText } from "./pistas.logic";

const es = {
  brandA: "Pistas",
  brandB: "futboleras",
  player: (n: number, total: number) => `Jugador ${n} / ${total}`,
  pointsInPlay: "Puntos en juego",
  score: "Tus puntos",
  revealClue: "Revelar pista",
  clueLocked: "Pista bloqueada",
  inputLabel: "Ingresá el apellido del jugador",
  inputPlaceholder: "Apellido…",
  inputHint: "Apellido o apodo · tildes y mayúsculas no importan",
  guess: "Adivinar",
  giveUp: "Me rindo",
  wrong: "Incorrecto",
  lastChance: (clues: number) => (clues > 0 ? `Última oportunidad: podés revelar ${clues === 1 ? "1 pista más" : `${clues} pistas más`} y tenés 1 intento.` : "Última oportunidad: tenés 1 intento."),
  solved: (n: number) => `¡Correcto! +${n}`,
  missed: "No lo sacaste",
  was: (name: string) => `Era ${name}`,
  revealLater: "La respuesta de hoy se ve mañana en «Días anteriores».",
  next: "Siguiente jugador",
  finish: "Ver resultado",
  kinds: { confed: "Confederación", position: "Posición", foot: "Pierna hábil", decade: "Década", fact: "Pista" } satisfies Record<ClueKind, string>,
  positions: { GK: "ARQ", DF: "DEF", MF: "MED", FW: "DEL" } as Record<string, string>,
  feet: { left: "Zurdo", right: "Diestro" } as Record<string, string>,
  intro: {
    lines: [
      "10 jugadores por día, cada uno con 10 pistas que van de lo más difícil a lo más fácil.",
      "Adiviná con la primera pista y ganás 10 puntos. Cada pista que pedís resta 1.",
      "Escribí el apellido (las tildes no importan). Si le errás, tenés 1 intento más y como máximo 3 pistas.",
    ],
    start: "Jugar",
    resume: (n: number) => `Seguir · jugador ${n}`,
    past: "Días anteriores",
    newBoard: "10 jugadores nuevos cada día a las 00:00 (hora de Argentina).",
    soon: "Las primeras pistas llegan pronto.",
  },
  end: {
    score: "Puntos",
    of: (max: number) => `de ${max}`,
    solved: "Adivinados",
    avgClues: "Pistas por acierto",
    streak: "Racha",
    days: (n: number) => (n === 1 ? "1 día" : `${n} días`),
    comeBack: "Mañana hay 10 jugadores nuevos.",
    share: "Compartir",
    whatsapp: "WhatsApp",
    copy: "Copiar",
    copied: "¡Copiado!",
    past: "Jugar días anteriores",
    more: "Más juegos",
    answers: "Respuestas",
    answersLater: "Las respuestas de hoy se ven mañana.",
    clues: (n: number) => (n === 1 ? "1 pista" : `${n} pistas`),
  },
  archive: { title: "Días anteriores", played: (s: number) => `${s} pts`, inProgress: "En curso", notPlayed: "Sin jugar", today: "Hoy", back: "Volver" },
  shareText: (n: number, score: number, grid: string, url: string) => `Pistas futboleras #${n} — ${score}/100\n${grid}\n¿Me superás? ${url}`,
  report: "Reportar un error en las pistas",
  reported: "¡Gracias! Lo revisamos.",
  exit: "Salir",
  loading: "Cargando las pistas…",
  loadError: "No pudimos cargar las pistas. Probá de nuevo en un rato.",
  retry: "Reintentar",
  actionError: "Se cortó la conexión. Probá de nuevo.",
  restarted: "Tu partida cambió (otro dispositivo o una corrección). La recargamos.",
  dayOver: "Terminó el día en Argentina: ya están los jugadores nuevos.",
  guestYesterday: "Estás jugando las pistas de un día anterior. Creá tu cuenta para jugar las de hoy y entrar al ranking.",
  playToday: "Jugar las de hoy",
  maintenance: "El juego está en mantenimiento. Volvé en un rato.",
  sessionChanged: "Cambió tu sesión. Arrancá de nuevo.",
  board: {
    title: "Ranking del día",
    players: (n: number) => (n === 1 ? "1 jugador terminó" : `${n} jugadores terminaron`),
    empty: "Todavía nadie terminó las pistas de hoy. ¡Sé el primero!",
    rank: (r: number) => `Puesto #${r}`,
    join: "Creá tu cuenta para entrar al ranking del día",
    joinButton: "Entrar al ranking",
    unranked: "Los días anteriores no suman al ranking.",
    guestPlay: "Jugás como invitado: tu puntaje no entra al ranking.",
  },
};

type Copy = typeof es;

const en: Copy = {
  brandA: "Football",
  brandB: "Clues",
  player: (n, total) => `Player ${n} / ${total}`,
  pointsInPlay: "Points in play",
  score: "Your points",
  revealClue: "Reveal clue",
  clueLocked: "Locked clue",
  inputLabel: "Type the player's surname",
  inputPlaceholder: "Surname…",
  inputHint: "Surname or nickname · accents and capitals don't matter",
  guess: "Guess",
  giveUp: "Give up",
  wrong: "Wrong",
  lastChance: (clues) => (clues > 0 ? `Last chance: you can reveal ${clues === 1 ? "1 more clue" : `${clues} more clues`} and you have 1 guess.` : "Last chance: you have 1 guess."),
  solved: (n) => `Correct! +${n}`,
  missed: "Not this time",
  was: (name) => `It was ${name}`,
  revealLater: "Today's answer shows up tomorrow under “Past days”.",
  next: "Next player",
  finish: "See result",
  kinds: { confed: "Confederation", position: "Position", foot: "Stronger foot", decade: "Decade", fact: "Clue" },
  positions: { GK: "GK", DF: "DEF", MF: "MID", FW: "FWD" },
  feet: { left: "Left", right: "Right" },
  intro: {
    lines: [
      "10 players a day, each with 10 clues that go from hardest to easiest.",
      "Guess on the first clue for 10 points. Every clue you ask for costs 1.",
      "Type the surname (accents don't matter). Miss once and you get 1 more guess and at most 3 more clues.",
    ],
    start: "Play",
    resume: (n) => `Continue · player ${n}`,
    past: "Past days",
    newBoard: "10 new players every day at 00:00 (Argentina time).",
    soon: "The first clues arrive soon.",
  },
  end: {
    score: "Points",
    of: (max) => `of ${max}`,
    solved: "Solved",
    avgClues: "Clues per solve",
    streak: "Streak",
    days: (n) => (n === 1 ? "1 day" : `${n} days`),
    comeBack: "10 new players tomorrow.",
    share: "Share",
    whatsapp: "WhatsApp",
    copy: "Copy",
    copied: "Copied!",
    past: "Play past days",
    more: "More games",
    answers: "Answers",
    answersLater: "Today's answers show up tomorrow.",
    clues: (n) => (n === 1 ? "1 clue" : `${n} clues`),
  },
  archive: { title: "Past days", played: (s) => `${s} pts`, inProgress: "In progress", notPlayed: "Not played", today: "Today", back: "Back" },
  shareText: (n, score, grid, url) => `Football Clues #${n} — ${score}/100\n${grid}\nCan you beat me? ${url}`,
  report: "Report a clue error",
  reported: "Thanks! We'll check it.",
  exit: "Exit",
  loading: "Loading the clues…",
  loadError: "We couldn't load the clues. Try again in a moment.",
  retry: "Retry",
  actionError: "Connection lost. Try again.",
  restarted: "Your game changed (another device or a correction). We reloaded it.",
  dayOver: "The day is over in Argentina: new players are ready.",
  guestYesterday: "You're playing a past day. Create an account to play today's and join the ranking.",
  playToday: "Play today's",
  maintenance: "The game is under maintenance. Come back soon.",
  sessionChanged: "Your session changed. Start again.",
  board: {
    title: "Today's ranking",
    players: (n) => (n === 1 ? "1 player finished" : `${n} players finished`),
    empty: "Nobody has finished today's clues yet. Be the first!",
    rank: (r) => `#${r} today`,
    join: "Create an account to join today's ranking",
    joinButton: "Join the ranking",
    unranked: "Past days don't count for the ranking.",
    guestPlay: "You're playing as a guest: your score isn't ranked.",
  },
};

const ka: Copy = {
  brandA: "საფეხბურთო",
  brandB: "მინიშნებები",
  player: (n, total) => `მოთამაშე ${n} / ${total}`,
  pointsInPlay: "ქულები თამაშში",
  score: "შენი ქულები",
  revealClue: "მინიშნების გახსნა",
  clueLocked: "დაბლოკილი მინიშნება",
  inputLabel: "ჩაწერე მოთამაშის გვარი",
  inputPlaceholder: "გვარი…",
  inputHint: "გვარი ან მეტსახელი · რეგისტრს მნიშვნელობა არ აქვს",
  guess: "გამოცნობა",
  giveUp: "ვნებდები",
  wrong: "არასწორია",
  lastChance: (clues) => (clues > 0 ? `ბოლო შანსი: შეგიძლია გახსნა კიდევ ${clues} მინიშნება და გაქვს 1 მცდელობა.` : "ბოლო შანსი: გაქვს 1 მცდელობა."),
  solved: (n) => `სწორია! +${n}`,
  missed: "ამჯერად ვერა",
  was: (name) => `ეს იყო ${name}`,
  revealLater: "დღევანდელი პასუხი ხვალ გამოჩნდება „წინა დღეებში“.",
  next: "შემდეგი მოთამაშე",
  finish: "შედეგის ნახვა",
  kinds: { confed: "კონფედერაცია", position: "პოზიცია", foot: "წამყვანი ფეხი", decade: "ათწლეული", fact: "მინიშნება" },
  positions: { GK: "მეკ", DF: "მცვ", MF: "ნახ", FW: "თავ" },
  feet: { left: "მარცხენა", right: "მარჯვენა" },
  intro: {
    lines: [
      "დღეში 10 მოთამაშე, თითოეულს 10 მინიშნება — რთულიდან მარტივისკენ.",
      "გამოიცანი პირველივე მინიშნებით და მიიღე 10 ქულა. ყოველი დამატებითი მინიშნება 1 ქულა ღირს.",
      "ჩაწერე გვარი (აქცენტებს მნიშვნელობა არ აქვს). თუ შეცდები, გექნება კიდევ 1 მცდელობა და მაქსიმუმ 3 მინიშნება.",
    ],
    start: "თამაში",
    resume: (n) => `გაგრძელება · მოთამაშე ${n}`,
    past: "წინა დღეები",
    newBoard: "10 ახალი მოთამაშე ყოველდღე 00:00-ზე (არგენტინის დროით).",
    soon: "პირველი მინიშნებები მალე გამოჩნდება.",
  },
  end: {
    score: "ქულა",
    of: (max) => `${max}-დან`,
    solved: "გამოცნობილი",
    avgClues: "მინიშნება გამოცნობაზე",
    streak: "სერია",
    days: (n) => `${n} დღე`,
    comeBack: "ხვალ 10 ახალი მოთამაშეა.",
    share: "გაზიარება",
    whatsapp: "WhatsApp",
    copy: "კოპირება",
    copied: "დაკოპირდა!",
    past: "წინა დღეების თამაში",
    more: "მეტი თამაში",
    answers: "პასუხები",
    answersLater: "დღევანდელი პასუხები ხვალ გამოჩნდება.",
    clues: (n) => `${n} მინიშნება`,
  },
  archive: { title: "წინა დღეები", played: (s) => `${s} ქულა`, inProgress: "მიმდინარე", notPlayed: "არ გითამაშია", today: "დღეს", back: "უკან" },
  shareText: (n, score, grid, url) => `საფეხბურთო მინიშნებები #${n} — ${score}/100\n${grid}\nმაჯობებ? ${url}`,
  report: "მინიშნებაში შეცდომის შეტყობინება",
  reported: "მადლობა! გადავამოწმებთ.",
  exit: "გასვლა",
  loading: "მინიშნებები იტვირთება…",
  loadError: "მინიშნებები ვერ ჩაიტვირთა. სცადე ცოტა ხანში.",
  retry: "თავიდან ცდა",
  actionError: "კავშირი გაწყდა. სცადე თავიდან.",
  restarted: "შენი თამაში შეიცვალა (სხვა მოწყობილობა ან შესწორება). თავიდან ჩავტვირთეთ.",
  dayOver: "არგენტინაში დღე დასრულდა: ახალი მოთამაშეები მზადაა.",
  guestYesterday: "წინა დღის მინიშნებებს თამაშობ. შექმენი ანგარიში, რომ ითამაშო დღევანდელი და მოხვდე რეიტინგში.",
  playToday: "დღევანდელის თამაში",
  maintenance: "თამაშზე ტექნიკური სამუშაოებია. დაბრუნდი ცოტა ხანში.",
  sessionChanged: "შენი სესია შეიცვალა. დაიწყე თავიდან.",
  board: {
    title: "დღის რეიტინგი",
    players: (n) => `${n} მოთამაშემ დაასრულა`,
    empty: "დღევანდელი მინიშნებები ჯერ არავის დაუსრულებია. იყავი პირველი!",
    rank: (r) => `#${r} დღეს`,
    join: "შექმენი ანგარიში და მოხვდი დღის რეიტინგში",
    joinButton: "რეიტინგში შესვლა",
    unranked: "წინა დღეები რეიტინგში არ ითვლება.",
    guestPlay: "სტუმრად თამაშობ: შენი ქულა რეიტინგში არ ითვლება.",
  },
};

const tr: Copy = {
  brandA: "Futbolcu",
  brandB: "Tahmini",
  player: (n, total) => `Oyuncu ${n} / ${total}`,
  pointsInPlay: "Oyundaki puan",
  score: "Puanın",
  revealClue: "İpucu aç",
  clueLocked: "Kilitli ipucu",
  inputLabel: "Oyuncunun soyadını yaz",
  inputPlaceholder: "Soyadı…",
  inputHint: "Soyadı veya lakabı · aksan ve büyük harf önemsiz",
  guess: "Tahmin et",
  giveUp: "Pes et",
  wrong: "Yanlış",
  lastChance: (clues) => (clues > 0 ? `Son şans: ${clues} ipucu daha açabilirsin ve 1 tahmin hakkın var.` : "Son şans: 1 tahmin hakkın var."),
  solved: (n) => `Doğru! +${n}`,
  missed: "Bu sefer olmadı",
  was: (name) => `Cevap: ${name}`,
  revealLater: "Bugünün cevabı yarın “Önceki günler” bölümünde görünür.",
  next: "Sonraki oyuncu",
  finish: "Sonucu gör",
  kinds: { confed: "Konfederasyon", position: "Mevki", foot: "Güçlü ayak", decade: "On yıl", fact: "İpucu" },
  positions: { GK: "KL", DF: "DF", MF: "OS", FW: "FV" },
  feet: { left: "Solak", right: "Sağ ayak" },
  intro: {
    lines: [
      "Her gün 10 oyuncu, her birinin zordan kolaya giden 10 ipucu var.",
      "İlk ipucunda bilirsen 10 puan. Açtığın her ipucu 1 puan düşürür.",
      "Soyadını yaz (aksanlar önemli değil). Yanlış yaparsan 1 hakkın ve en fazla 3 ipucun daha kalır.",
    ],
    start: "Oyna",
    resume: (n) => `Devam et · oyuncu ${n}`,
    past: "Önceki günler",
    newBoard: "Her gün 00:00'da 10 yeni oyuncu (Arjantin saati).",
    soon: "İlk ipuçları yakında geliyor.",
  },
  end: {
    score: "Puan",
    of: (max) => `/ ${max}`,
    solved: "Bilinen",
    avgClues: "Bilme başına ipucu",
    streak: "Seri",
    days: (n) => `${n} gün`,
    comeBack: "Yarın 10 yeni oyuncu var.",
    share: "Paylaş",
    whatsapp: "WhatsApp",
    copy: "Kopyala",
    copied: "Kopyalandı!",
    past: "Önceki günleri oyna",
    more: "Daha fazla oyun",
    answers: "Cevaplar",
    answersLater: "Bugünün cevapları yarın görünür.",
    clues: (n) => `${n} ipucu`,
  },
  archive: { title: "Önceki günler", played: (s) => `${s} puan`, inProgress: "Devam ediyor", notPlayed: "Oynanmadı", today: "Bugün", back: "Geri" },
  shareText: (n, score, grid, url) => `Futbolcu Tahmin Etme Oyunu #${n} — ${score}/100\n${grid}\nBeni geçebilir misin? ${url}`,
  report: "İpucunda hata bildir",
  reported: "Teşekkürler! Kontrol edeceğiz.",
  exit: "Çıkış",
  loading: "İpuçları yükleniyor…",
  loadError: "İpuçları yüklenemedi. Biraz sonra tekrar dene.",
  retry: "Tekrar dene",
  actionError: "Bağlantı koptu. Tekrar dene.",
  restarted: "Oyunun değişti (başka bir cihaz ya da bir düzeltme). Yeniden yükledik.",
  dayOver: "Arjantin'de gün bitti: yeni oyuncular hazır.",
  guestYesterday: "Önceki bir günü oynuyorsun. Bugününkünü oynamak ve sıralamaya girmek için hesap oluştur.",
  playToday: "Bugününkünü oyna",
  maintenance: "Oyun bakımda. Birazdan tekrar gel.",
  sessionChanged: "Oturumun değişti. Baştan başla.",
  board: {
    title: "Günün sıralaması",
    players: (n) => `${n} oyuncu bitirdi`,
    empty: "Bugünün ipuçlarını henüz kimse bitirmedi. İlk sen ol!",
    rank: (r) => `Bugün #${r}`,
    join: "Günün sıralamasına girmek için hesap oluştur",
    joinButton: "Sıralamaya gir",
    unranked: "Önceki günler sıralamaya sayılmaz.",
    guestPlay: "Misafir olarak oynuyorsun: puanın sıralamaya girmez.",
  },
};

const COPY: Record<string, Copy> = { es, en, ka, tr };

export const pistasCopy = (locale: string): Copy => COPY[locale] ?? en;

/** Clue text in the page locale; ka/tr fall back to English, then Spanish. */
export const textFor = (text: LocalizedText, locale: string): string =>
  (locale === "ka" ? text.ka : locale === "tr" ? text.tr : locale === "es" ? text.es : text.en) || text.en || text.es;
