/**
 * Canonical list of all screen names used for navigation.
 * Single source of truth for screen types across the app.
 */
export type Screen =
  | "welcome"
  | "login"
  | "register"
  | "forgotPassword"
  | "onboarding"
  | "home"
  | "quizBall"
  | "quizBallMatchmaking"
  | "quizBallShowdown"
  | "quizBallFriendMatch"
  | "quizBallGame"
  | "quizBallResults"
  | "modeSelection"
  | "matchType"
  | "friendMatch"
  | "matchmaking"
  | "rankedMatchmaking"
  | "rankedCategoryBlocking"
  | "rankedShowdown"
  | "rankedGame"
  | "buzzerMatchmaking"
  | "buzzerShowdown"
  | "buzzerResults"
  | "showdown"
  | "roundIntro"
  | "roundTransition"
  | "roundResult"
  | "game"
  | "results"
  | "leaderboard"
  | "profile"
  | "store"
  | "settings"
  | "dailyChallenges"
  | "dailyRewards"
  | "objectives"
  | "careerMode"
  | "managerCareer"
  | "teamSelection"
  | "tournaments"
  | "tournamentWaiting"
  | "tournamentGame"
  | "tournamentResults"
  | "terms"
  | "privacy"
  | "oauthCallback";
