import type { OpponentLocationCandidate } from "./cities";

/**
 * When the backend gives us a country but no coordinates, this map
 * decides which city to drop the pin on. Keys are normalized country
 * slugs (lowercase, underscore-separated) — see COUNTRY_CODE_TO_KEY
 * and COUNTRY_ALIASES for the input formats we accept.
 */
export const COUNTRY_LOCATION_FALLBACKS: Record<string, OpponentLocationCandidate> = {
  usa: { lon: -104.99, lat: 39.74, city: "Denver", country: "USA", flag: "🇺🇸" },
  mexico: {
    lon: -99.1,
    lat: 19.4,
    city: "Mexico City",
    country: "Mexico",
    flag: "🇲🇽",
  },
  brazil: {
    lon: -47.88,
    lat: -15.79,
    city: "Brasilia",
    country: "Brazil",
    flag: "🇧🇷",
  },
  uk: { lon: -1.9, lat: 52.5, city: "Birmingham", country: "UK", flag: "🇬🇧" },
  france: {
    lon: 4.83,
    lat: 45.76,
    city: "Lyon",
    country: "France",
    flag: "🇫🇷",
  },
  germany: {
    lon: 11.58,
    lat: 48.14,
    city: "Munich",
    country: "Germany",
    flag: "🇩🇪",
  },
  turkey: {
    lon: 32.86,
    lat: 39.93,
    city: "Ankara",
    country: "Turkey",
    flag: "🇹🇷",
  },
  saudi_arabia: {
    lon: 46.71,
    lat: 24.71,
    city: "Riyadh",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  india: {
    lon: 77.21,
    lat: 28.61,
    city: "Delhi",
    country: "India",
    flag: "🇮🇳",
  },
  thailand: {
    lon: 98.98,
    lat: 18.79,
    city: "Chiang Mai",
    country: "Thailand",
    flag: "🇹🇭",
  },
  china: {
    lon: 104.06,
    lat: 30.67,
    city: "Chengdu",
    country: "China",
    flag: "🇨🇳",
  },
  japan: {
    lon: 141.35,
    lat: 43.06,
    city: "Sapporo",
    country: "Japan",
    flag: "🇯🇵",
  },
  australia: {
    lon: 133.88,
    lat: -23.7,
    city: "Alice Springs",
    country: "Australia",
    flag: "🇦🇺",
  },
  kenya: {
    lon: 36.82,
    lat: -1.29,
    city: "Nairobi",
    country: "Kenya",
    flag: "🇰🇪",
  },
  nigeria: {
    lon: 7.49,
    lat: 9.06,
    city: "Abuja",
    country: "Nigeria",
    flag: "🇳🇬",
  },
  argentina: {
    lon: -64.19,
    lat: -31.42,
    city: "Cordoba",
    country: "Argentina",
    flag: "🇦🇷",
  },
  spain: {
    lon: -3.7,
    lat: 40.42,
    city: "Madrid",
    country: "Spain",
    flag: "🇪🇸",
  },
  italy: { lon: 12.5, lat: 41.9, city: "Rome", country: "Italy", flag: "🇮🇹" },
  portugal: {
    lon: -8.62,
    lat: 41.16,
    city: "Porto",
    country: "Portugal",
    flag: "🇵🇹",
  },
  netherlands: {
    lon: 5.12,
    lat: 52.09,
    city: "Utrecht",
    country: "Netherlands",
    flag: "🇳🇱",
  },
  russia: {
    lon: 37.62,
    lat: 55.75,
    city: "Moscow",
    country: "Russia",
    flag: "🇷🇺",
  },
  canada: {
    lon: -113.49,
    lat: 53.55,
    city: "Edmonton",
    country: "Canada",
    flag: "🇨🇦",
  },
  morocco: {
    lon: -7.59,
    lat: 33.57,
    city: "Casablanca",
    country: "Morocco",
    flag: "🇲🇦",
  },
  chile: { lon: -70.66, lat: -33.45, city: "Santiago", country: "Chile", flag: "🇨🇱" },
  colombia: { lon: -74.07, lat: 4.71, city: "Bogota", country: "Colombia", flag: "🇨🇴" },
  peru: { lon: -76.9, lat: -11.9, city: "Lima", country: "Peru", flag: "🇵🇪" },
  uruguay: { lon: -56.52, lat: -33.38, city: "Durazno", country: "Uruguay", flag: "🇺🇾" },
  paraguay: { lon: -57.58, lat: -25.26, city: "Asuncion", country: "Paraguay", flag: "🇵🇾" },
  bolivia: { lon: -68.12, lat: -16.5, city: "La Paz", country: "Bolivia", flag: "🇧🇴" },
  ecuador: { lon: -78.47, lat: -0.18, city: "Quito", country: "Ecuador", flag: "🇪🇨" },
  venezuela: { lon: -68.0, lat: 10.16, city: "Valencia", country: "Venezuela", flag: "🇻🇪" },
  costa_rica: { lon: -84.08, lat: 9.93, city: "San Jose", country: "Costa Rica", flag: "🇨🇷" },
  panama: { lon: -80.98, lat: 8.1, city: "Santiago", country: "Panama", flag: "🇵🇦" },
  dominican_republic: { lon: -69.93, lat: 18.48, city: "Santo Domingo", country: "Dominican Republic", flag: "🇩🇴" },
  ireland: { lon: -7.94, lat: 53.42, city: "Athlone", country: "Ireland", flag: "🇮🇪" },
  belgium: { lon: 4.35, lat: 50.85, city: "Brussels", country: "Belgium", flag: "🇧🇪" },
  switzerland: { lon: 7.45, lat: 46.95, city: "Bern", country: "Switzerland", flag: "🇨🇭" },
  austria: { lon: 16.37, lat: 48.21, city: "Vienna", country: "Austria", flag: "🇦🇹" },
  poland: { lon: 21.01, lat: 52.23, city: "Warsaw", country: "Poland", flag: "🇵🇱" },
  czech_republic: { lon: 14.44, lat: 50.08, city: "Prague", country: "Czech Republic", flag: "🇨🇿" },
  denmark: { lon: 10.2, lat: 56.16, city: "Aarhus", country: "Denmark", flag: "🇩🇰" },
  sweden: { lon: 15.21, lat: 59.27, city: "Orebro", country: "Sweden", flag: "🇸🇪" },
  norway: { lon: 10.47, lat: 61.12, city: "Lillehammer", country: "Norway", flag: "🇳🇴" },
  finland: { lon: 23.76, lat: 61.5, city: "Tampere", country: "Finland", flag: "🇫🇮" },
  greece: { lon: 22.42, lat: 39.64, city: "Larissa", country: "Greece", flag: "🇬🇷" },
  romania: { lon: 26.1, lat: 44.43, city: "Bucharest", country: "Romania", flag: "🇷🇴" },
  ukraine: { lon: 30.52, lat: 50.45, city: "Kyiv", country: "Ukraine", flag: "🇺🇦" },
  serbia: { lon: 20.46, lat: 44.82, city: "Belgrade", country: "Serbia", flag: "🇷🇸" },
  croatia: { lon: 15.98, lat: 45.81, city: "Zagreb", country: "Croatia", flag: "🇭🇷" },
  hungary: { lon: 19.04, lat: 47.5, city: "Budapest", country: "Hungary", flag: "🇭🇺" },
  bulgaria: { lon: 23.32, lat: 42.7, city: "Sofia", country: "Bulgaria", flag: "🇧🇬" },
  slovakia: { lon: 17.11, lat: 48.15, city: "Bratislava", country: "Slovakia", flag: "🇸🇰" },
  slovenia: { lon: 14.51, lat: 46.06, city: "Ljubljana", country: "Slovenia", flag: "🇸🇮" },
  albania: { lon: 19.82, lat: 41.33, city: "Tirana", country: "Albania", flag: "🇦🇱" },
  bosnia: { lon: 18.41, lat: 43.86, city: "Sarajevo", country: "Bosnia and Herzegovina", flag: "🇧🇦" },
  north_macedonia: { lon: 21.43, lat: 42.0, city: "Skopje", country: "North Macedonia", flag: "🇲🇰" },
  lithuania: { lon: 25.28, lat: 54.69, city: "Vilnius", country: "Lithuania", flag: "🇱🇹" },
  latvia: { lon: 24.1, lat: 56.95, city: "Riga", country: "Latvia", flag: "🇱🇻" },
  estonia: { lon: 26.73, lat: 58.38, city: "Tartu", country: "Estonia", flag: "🇪🇪" },
  israel: { lon: 35.21, lat: 31.77, city: "Jerusalem", country: "Israel", flag: "🇮🇱" },
  uae: { lon: 55.75, lat: 24.21, city: "Al Ain", country: "UAE", flag: "🇦🇪" },
  qatar: { lon: 51.53, lat: 25.29, city: "Doha", country: "Qatar", flag: "🇶🇦" },
  egypt: { lon: 31.24, lat: 30.04, city: "Cairo", country: "Egypt", flag: "🇪🇬" },
  south_africa: { lon: 28.05, lat: -26.2, city: "Johannesburg", country: "South Africa", flag: "🇿🇦" },
  ghana: { lon: -1.62, lat: 6.69, city: "Kumasi", country: "Ghana", flag: "🇬🇭" },
  senegal: { lon: -13.67, lat: 13.77, city: "Tambacounda", country: "Senegal", flag: "🇸🇳" },
  algeria: { lon: 5.41, lat: 36.19, city: "Setif", country: "Algeria", flag: "🇩🇿" },
  tunisia: { lon: 10.1, lat: 35.68, city: "Kairouan", country: "Tunisia", flag: "🇹🇳" },
  ethiopia: { lon: 38.76, lat: 9.03, city: "Addis Ababa", country: "Ethiopia", flag: "🇪🇹" },
  tanzania: { lon: 35.74, lat: -6.16, city: "Dodoma", country: "Tanzania", flag: "🇹🇿" },
  uganda: { lon: 32.58, lat: 0.35, city: "Kampala", country: "Uganda", flag: "🇺🇬" },
  ivory_coast: { lon: -5.28, lat: 6.82, city: "Yamoussoukro", country: "Ivory Coast", flag: "🇨🇮" },
  cameroon: { lon: 11.52, lat: 3.85, city: "Yaounde", country: "Cameroon", flag: "🇨🇲" },
  dr_congo: { lon: 15.31, lat: -4.32, city: "Kinshasa", country: "DR Congo", flag: "🇨🇩" },
  zimbabwe: { lon: 31.05, lat: -17.83, city: "Harare", country: "Zimbabwe", flag: "🇿🇼" },
  zambia: { lon: 28.28, lat: -15.39, city: "Lusaka", country: "Zambia", flag: "🇿🇲" },
  angola: { lon: 15.75, lat: -12.78, city: "Huambo", country: "Angola", flag: "🇦🇴" },
  pakistan: { lon: 73.05, lat: 33.68, city: "Islamabad", country: "Pakistan", flag: "🇵🇰" },
  bangladesh: { lon: 90.41, lat: 23.81, city: "Dhaka", country: "Bangladesh", flag: "🇧🇩" },
  indonesia: { lon: 107.62, lat: -6.92, city: "Bandung", country: "Indonesia", flag: "🇮🇩" },
  malaysia: { lon: 101.69, lat: 3.14, city: "Kuala Lumpur", country: "Malaysia", flag: "🇲🇾" },
  singapore: { lon: 103.82, lat: 1.35, city: "Singapore", country: "Singapore", flag: "🇸🇬" },
  philippines: { lon: 121.04, lat: 14.68, city: "Quezon City", country: "Philippines", flag: "🇵🇭" },
  vietnam: { lon: 105.85, lat: 21.03, city: "Hanoi", country: "Vietnam", flag: "🇻🇳" },
  south_korea: { lon: 127.38, lat: 36.35, city: "Daejeon", country: "South Korea", flag: "🇰🇷" },
  iran: { lon: 51.39, lat: 35.69, city: "Tehran", country: "Iran", flag: "🇮🇷" },
  iraq: { lon: 44.36, lat: 33.31, city: "Baghdad", country: "Iraq", flag: "🇮🇶" },
  jordan: { lon: 35.93, lat: 31.95, city: "Amman", country: "Jordan", flag: "🇯🇴" },
  lebanon: { lon: 35.5, lat: 33.89, city: "Beirut", country: "Lebanon", flag: "🇱🇧" },
  new_zealand: { lon: 175.28, lat: -37.78, city: "Hamilton", country: "New Zealand", flag: "🇳🇿" },
  taiwan: { lon: 120.67, lat: 24.15, city: "Taichung", country: "Taiwan", flag: "🇹🇼" },
  georgia: {
    lon: 44.79,
    lat: 41.72,
    city: "Tbilisi",
    country: "Georgia",
    flag: "🇬🇪",
  },
};

/**
 * ISO-3166-1 alpha-2 codes (plus a couple of legacy variants the API
 * still emits) mapped to our internal country slug.
 */
export const COUNTRY_CODE_TO_KEY: Record<string, string> = {
  US: "usa",
  MX: "mexico",
  BR: "brazil",
  GB: "uk",
  UK: "uk",
  FR: "france",
  DE: "germany",
  TR: "turkey",
  SA: "saudi_arabia",
  IN: "india",
  TH: "thailand",
  CN: "china",
  JP: "japan",
  AU: "australia",
  KE: "kenya",
  NG: "nigeria",
  AR: "argentina",
  ES: "spain",
  IT: "italy",
  PT: "portugal",
  NL: "netherlands",
  RU: "russia",
  CA: "canada",
  MA: "morocco",
  CL: "chile",
  CO: "colombia",
  PE: "peru",
  UY: "uruguay",
  PY: "paraguay",
  BO: "bolivia",
  EC: "ecuador",
  VE: "venezuela",
  CR: "costa_rica",
  PA: "panama",
  DO: "dominican_republic",
  IE: "ireland",
  BE: "belgium",
  CH: "switzerland",
  AT: "austria",
  PL: "poland",
  CZ: "czech_republic",
  DK: "denmark",
  SE: "sweden",
  NO: "norway",
  FI: "finland",
  GR: "greece",
  RO: "romania",
  UA: "ukraine",
  RS: "serbia",
  HR: "croatia",
  HU: "hungary",
  BG: "bulgaria",
  SK: "slovakia",
  SI: "slovenia",
  AL: "albania",
  BA: "bosnia",
  MK: "north_macedonia",
  LT: "lithuania",
  LV: "latvia",
  EE: "estonia",
  IL: "israel",
  AE: "uae",
  QA: "qatar",
  EG: "egypt",
  ZA: "south_africa",
  GH: "ghana",
  SN: "senegal",
  DZ: "algeria",
  TN: "tunisia",
  ET: "ethiopia",
  TZ: "tanzania",
  UG: "uganda",
  CI: "ivory_coast",
  CM: "cameroon",
  CD: "dr_congo",
  ZW: "zimbabwe",
  ZM: "zambia",
  AO: "angola",
  PK: "pakistan",
  BD: "bangladesh",
  ID: "indonesia",
  MY: "malaysia",
  SG: "singapore",
  PH: "philippines",
  VN: "vietnam",
  KR: "south_korea",
  IR: "iran",
  IQ: "iraq",
  JO: "jordan",
  LB: "lebanon",
  NZ: "new_zealand",
  TW: "taiwan",
  GE: "georgia",
};

/**
 * Free-text variants of each country we accept — used after lowercasing
 * + stripping punctuation. Flag emojis are included so payloads with
 * just an emoji still resolve to the right country.
 */
export const COUNTRY_ALIASES: Record<string, string[]> = {
  usa: [
    "usa",
    "united states",
    "united states of america",
    "america",
    "u s a",
    "🇺🇸",
  ],
  mexico: ["mexico", "mexican", "🇲🇽"],
  brazil: ["brazil", "brasil", "🇧🇷"],
  uk: ["uk", "united kingdom", "britain", "england", "🇬🇧"],
  france: ["france", "french", "🇫🇷"],
  germany: ["germany", "german", "deutschland", "🇩🇪"],
  turkey: ["turkey", "turkiye", "🇹🇷"],
  saudi_arabia: ["saudi", "saudi arabia", "🇸🇦"],
  india: ["india", "indian", "🇮🇳"],
  thailand: ["thailand", "thai", "🇹🇭"],
  china: ["china", "chinese", "🇨🇳"],
  japan: ["japan", "japanese", "🇯🇵"],
  australia: ["australia", "australian", "🇦🇺"],
  kenya: ["kenya", "kenyan", "🇰🇪"],
  nigeria: ["nigeria", "nigerian", "🇳🇬"],
  argentina: ["argentina", "argentinian", "🇦🇷"],
  spain: ["spain", "spanish", "espana", "🇪🇸"],
  italy: ["italy", "italian", "italia", "🇮🇹"],
  portugal: ["portugal", "portuguese", "🇵🇹"],
  netherlands: ["netherlands", "dutch", "holland", "🇳🇱"],
  russia: ["russia", "russian", "🇷🇺"],
  canada: ["canada", "canadian", "🇨🇦"],
  morocco: ["morocco", "moroccan", "casablanca", "rabat", "marrakesh", "marrakech", "🇲🇦"],
  czech_republic: ["czech republic", "czechia", "czech", "🇨🇿"],
  bosnia: ["bosnia", "bosnia and herzegovina", "herzegovina", "🇧🇦"],
  north_macedonia: ["north macedonia", "macedonia", "🇲🇰"],
  uae: ["uae", "u a e", "united arab emirates", "emirates", "🇦🇪"],
  south_africa: ["south africa", "south african", "🇿🇦"],
  ivory_coast: ["ivory coast", "cote d ivoire", "côte d'ivoire", "cote divoire", "🇨🇮"],
  dr_congo: ["dr congo", "d r congo", "democratic republic of congo", "congo kinshasa", "🇨🇩"],
  south_korea: ["south korea", "korea", "korean", "republic of korea", "🇰🇷"],
  new_zealand: ["new zealand", "kiwi", "🇳🇿"],
  georgia: ["georgia", "georgian", "sakartvelo", "🇬🇪"],
};

/**
 * City-name hints we use to infer a country when the payload only
 * mentions a city (or includes one alongside the country). Keys are
 * the country slug; values are city names that strongly imply it.
 */
export const CITY_ALIASES: Record<string, string[]> = {
  usa: [
    "new york",
    "nyc",
    "denver",
    "chicago",
    "los angeles",
    "miami",
    "seattle",
    "dallas",
    "houston",
    "phoenix",
    "atlanta",
    "boston",
  ],
  mexico: ["mexico city", "guadalajara", "monterrey"],
  brazil: ["brasilia", "sao paulo", "rio de janeiro", "rio"],
  uk: ["london", "birmingham", "manchester", "liverpool"],
  france: ["paris", "lyon", "marseille"],
  germany: ["munich", "berlin", "hamburg", "frankfurt"],
  turkey: ["ankara", "istanbul"],
  saudi_arabia: ["riyadh", "jeddah"],
  india: ["delhi", "mumbai", "bangalore", "bengaluru"],
  thailand: ["chiang mai", "bangkok"],
  china: ["chengdu", "beijing", "shanghai", "guangzhou"],
  japan: ["sapporo", "tokyo", "osaka"],
  australia: ["alice springs", "sydney", "melbourne", "perth"],
  kenya: ["nairobi"],
  nigeria: ["abuja", "lagos"],
  argentina: ["cordoba", "buenos aires"],
  spain: ["madrid", "barcelona", "valencia"],
  italy: ["rome", "milan", "naples"],
  portugal: ["porto", "lisbon"],
  netherlands: ["utrecht", "amsterdam", "rotterdam"],
  russia: ["moscow", "saint petersburg"],
  canada: ["edmonton", "toronto", "vancouver", "montreal"],
  morocco: ["casablanca", "rabat", "marrakesh", "marrakech"],
  chile: ["santiago", "valparaiso"],
  colombia: ["bogota", "medellin", "cali"],
  peru: ["lima", "cusco", "arequipa"],
  uruguay: ["montevideo", "durazno"],
  paraguay: ["asuncion"],
  bolivia: ["la paz", "sucre", "santa cruz"],
  ecuador: ["quito", "guayaquil"],
  // "valencia" omitted — it collides with Spain's (more prominent) Valencia and
  // would mis-route a city-only payload here.
  venezuela: ["caracas"],
  costa_rica: ["san jose"],
  // "santiago" omitted — it collides with Chile's (more prominent) Santiago.
  panama: ["panama city"],
  dominican_republic: ["santo domingo"],
  ireland: ["dublin", "athlone", "cork", "galway"],
  belgium: ["brussels", "antwerp"],
  switzerland: ["bern", "zurich", "geneva"],
  austria: ["vienna", "graz"],
  poland: ["warsaw", "krakow"],
  czech_republic: ["prague", "brno"],
  denmark: ["copenhagen", "aarhus"],
  sweden: ["stockholm", "orebro", "gothenburg"],
  norway: ["oslo", "lillehammer", "bergen"],
  finland: ["helsinki", "tampere"],
  greece: ["athens", "larissa", "thessaloniki"],
  romania: ["bucharest", "cluj"],
  ukraine: ["kyiv", "kiev", "lviv"],
  serbia: ["belgrade"],
  croatia: ["zagreb", "split"],
  hungary: ["budapest"],
  bulgaria: ["sofia"],
  slovakia: ["bratislava"],
  slovenia: ["ljubljana"],
  albania: ["tirana"],
  bosnia: ["sarajevo"],
  north_macedonia: ["skopje"],
  lithuania: ["vilnius", "kaunas"],
  latvia: ["riga"],
  estonia: ["tartu", "tallinn"],
  israel: ["jerusalem", "tel aviv"],
  uae: ["dubai", "abu dhabi", "al ain"],
  qatar: ["doha"],
  egypt: ["cairo", "alexandria"],
  south_africa: ["johannesburg", "cape town", "pretoria"],
  ghana: ["accra", "kumasi"],
  senegal: ["dakar", "tambacounda"],
  algeria: ["algiers", "setif", "oran"],
  tunisia: ["tunis", "kairouan"],
  ethiopia: ["addis ababa"],
  tanzania: ["dodoma", "dar es salaam"],
  uganda: ["kampala"],
  ivory_coast: ["yamoussoukro", "abidjan"],
  cameroon: ["yaounde", "douala"],
  dr_congo: ["kinshasa"],
  zimbabwe: ["harare"],
  zambia: ["lusaka"],
  angola: ["luanda", "huambo"],
  pakistan: ["islamabad", "lahore", "karachi"],
  bangladesh: ["dhaka"],
  indonesia: ["jakarta", "bandung"],
  malaysia: ["kuala lumpur"],
  singapore: ["singapore"],
  philippines: ["manila", "quezon city"],
  vietnam: ["hanoi", "ho chi minh"],
  south_korea: ["seoul", "daejeon", "busan"],
  iran: ["tehran"],
  iraq: ["baghdad"],
  jordan: ["amman"],
  lebanon: ["beirut"],
  new_zealand: ["auckland", "wellington", "hamilton"],
  taiwan: ["taipei", "taichung"],
  georgia: ["tbilisi", "batumi", "kutaisi"],
};

/**
 * Direct city → coordinate lookups for cases where the country
 * fallback isn't precise enough. Keys are lowercase city names.
 */
export const CITY_LOCATION_OVERRIDES: Record<string, OpponentLocationCandidate> = {
  "new york": {
    lon: -74.75,
    lat: 40.9,
    city: "New York",
    country: "USA",
    flag: "🇺🇸",
  },
  "new york city": {
    lon: -74.75,
    lat: 40.9,
    city: "New York",
    country: "USA",
    flag: "🇺🇸",
  },
  nyc: {
    lon: -74.75,
    lat: 40.9,
    city: "New York",
    country: "USA",
    flag: "🇺🇸",
  },
  denver: {
    lon: -104.99,
    lat: 39.74,
    city: "Denver",
    country: "USA",
    flag: "🇺🇸",
  },
  chicago: {
    lon: -87.63,
    lat: 41.88,
    city: "Chicago",
    country: "USA",
    flag: "🇺🇸",
  },
  "los angeles": {
    lon: -117.65,
    lat: 34.15,
    city: "Los Angeles",
    country: "USA",
    flag: "🇺🇸",
  },
  "mexico city": {
    lon: -99.1,
    lat: 19.4,
    city: "Mexico City",
    country: "Mexico",
    flag: "🇲🇽",
  },
  brasilia: {
    lon: -47.88,
    lat: -15.79,
    city: "Brasilia",
    country: "Brazil",
    flag: "🇧🇷",
  },
  birmingham: {
    lon: -1.9,
    lat: 52.5,
    city: "Birmingham",
    country: "UK",
    flag: "🇬🇧",
  },
  lyon: { lon: 4.83, lat: 45.76, city: "Lyon", country: "France", flag: "🇫🇷" },
  munich: {
    lon: 11.58,
    lat: 48.14,
    city: "Munich",
    country: "Germany",
    flag: "🇩🇪",
  },
  ankara: {
    lon: 32.86,
    lat: 39.93,
    city: "Ankara",
    country: "Turkey",
    flag: "🇹🇷",
  },
  riyadh: {
    lon: 46.71,
    lat: 24.71,
    city: "Riyadh",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  delhi: {
    lon: 77.21,
    lat: 28.61,
    city: "Delhi",
    country: "India",
    flag: "🇮🇳",
  },
  "chiang mai": {
    lon: 98.98,
    lat: 18.79,
    city: "Chiang Mai",
    country: "Thailand",
    flag: "🇹🇭",
  },
  chengdu: {
    lon: 104.06,
    lat: 30.67,
    city: "Chengdu",
    country: "China",
    flag: "🇨🇳",
  },
  sapporo: {
    lon: 141.35,
    lat: 43.06,
    city: "Sapporo",
    country: "Japan",
    flag: "🇯🇵",
  },
  nairobi: {
    lon: 36.82,
    lat: -1.29,
    city: "Nairobi",
    country: "Kenya",
    flag: "🇰🇪",
  },
  abuja: {
    lon: 7.49,
    lat: 9.06,
    city: "Abuja",
    country: "Nigeria",
    flag: "🇳🇬",
  },
  moscow: {
    lon: 37.62,
    lat: 55.75,
    city: "Moscow",
    country: "Russia",
    flag: "🇷🇺",
  },
  casablanca: {
    lon: -7.59,
    lat: 33.57,
    city: "Casablanca",
    country: "Morocco",
    flag: "🇲🇦",
  },
  rabat: {
    lon: -6.84,
    lat: 34.02,
    city: "Rabat",
    country: "Morocco",
    flag: "🇲🇦",
  },
  tbilisi: {
    lon: 44.79,
    lat: 41.72,
    city: "Tbilisi",
    country: "Georgia",
    flag: "🇬🇪",
  },
  batumi: {
    lon: 41.64,
    lat: 41.65,
    city: "Batumi",
    country: "Georgia",
    flag: "🇬🇪",
  },
  kutaisi: {
    lon: 42.7,
    lat: 42.27,
    city: "Kutaisi",
    country: "Georgia",
    flag: "🇬🇪",
  },
};
