import type { Competition, LocalizedName, MinutoLocale, Stage } from "./minuto.logic";

const es = {
  brandA: "¿En qué",
  brandB: "minuto?",
  pageName: "Adivina el minuto exacto del gol",
  round: (n: number, total: number) => `Gol ${n} / ${total}`,
  withData: "Con datos",
  score: "Tus puntos",
  scoredBy: "Gol de",
  goalOf: (a: number, b: number) => `Gol del ${a}-${b}`,
  penalty: "de penal",
  aet: "Prórroga",
  leg: { 1: "Ida", 2: "Vuelta" } as Record<number, string>,
  stages: { final: "Final", third: "Tercer puesto", semi: "Semifinal", quarter: "Cuartos de final", r16: "Octavos de final", r32: "16avos de final", group: "Fase de grupos", playoff: "Repechaje", other: "" } satisfies Record<Stage, string>,
  group: (g: string) => `Grupo ${g}`,
  comps: { FIWC: "Mundial", EURO: "Eurocopa", COPA: "Copa América", CL: "Champions League", EL: "Europa League", CLI: "Libertadores", KLUB: "Mundial de Clubes", USC: "Supercopa de Europa" } satisfies Record<Competition, string>,
  inputLabel: "¿En qué minuto fue?",
  minuteBox: "Minuto",
  seatScore: (name: string, points: number) => `${name}: ${points} ${points === 1 ? "punto" : "puntos"}`,
  inputPlaceholder: "Minuto",
  inputHint: "Tiempo añadido: 45+2 → escribí 47",
  invalidMinute: "Escribí un minuto entre 1 y 130.",
  confirm: "Confirmar",
  exact: "¡Minuto exacto! +3",
  off: (diff: number, points: number) => `A ${diff === 1 ? "1 minuto" : `${diff} minutos`}${points > 0 ? ` · +${points}` : ""}`,
  was: (minute: string) => `Fue en el ${minute}`,
  yourGuess: (minute: string) => `Tu respuesta: ${minute}`,
  next: "Siguiente gol",
  finish: "Ver resultado",
  photo: "Foto",
  intro: {
    lines: [
      "10 goles famosos por día: adiviná en qué minuto entró cada uno.",
      "Minuto exacto: 3 puntos. A 2 minutos o menos: 2. A 5 o menos: 1.",
      "El tiempo añadido se suma: un gol en el 90+3 es el minuto 93.",
    ],
    start: "Jugar",
    resume: (n: number) => `Seguir · gol ${n}`,
    past: "Días anteriores",
    newBoard: "10 goles nuevos cada día a las 00:00 (hora de Argentina).",
    soon: "Los primeros goles llegan pronto.",
  },
  end: {
    score: "Puntos",
    of: (max: number) => `de ${max}`,
    exact: "Exactos",
    avgOff: "Error promedio",
    minutes: (n: string) => `${n} min`,
    streak: "Racha",
    days: (n: number) => (n === 1 ? "1 día" : `${n} días`),
    comeBack: "Mañana hay 10 goles nuevos.",
    share: "Compartir",
    whatsapp: "WhatsApp",
    copy: "Copiar",
    copied: "¡Copiado!",
    past: "Jugar días anteriores",
    more: "Más juegos",
    answers: "Los goles",
    you: "Vos",
  },
  archive: { title: "Días anteriores", played: (s: number) => `${s} pts`, inProgress: "En curso", notPlayed: "Sin jugar", today: "Hoy", back: "Volver" },
  shareText: (n: number, score: number, grid: string, url: string) => `¿En qué minuto? #${n} — ${score}/30\n${grid}\n¿Me superás? ${url}`,
  report: "Reportar un error en este gol",
  reported: "¡Gracias! Lo revisamos.",
  exit: "Salir",
  loading: "Cargando los goles…",
  loadError: "No pudimos cargar los goles. Probá de nuevo en un rato.",
  retry: "Reintentar",
  actionError: "Se cortó la conexión. Probá de nuevo.",
  restarted: "Tu partida cambió (otro dispositivo o una corrección). La recargamos.",
  dayOver: "Terminó el día en Argentina: ya están los goles nuevos.",
  guestYesterday: "Estás jugando los goles de un día anterior. Creá tu cuenta para jugar los de hoy y entrar al ranking.",
  playToday: "Jugar los de hoy",
  maintenance: "El juego está en mantenimiento. Volvé en un rato.",
  sessionChanged: "Cambió tu sesión. Arrancá de nuevo.",
  board: {
    title: "Ranking del día",
    players: (n: number) => (n === 1 ? "1 jugador terminó" : `${n} jugadores terminaron`),
    empty: "Todavía nadie terminó los goles de hoy. ¡Sé el primero!",
    rank: (r: number) => `Puesto #${r}`,
    join: "Creá tu cuenta para entrar al ranking del día",
    joinButton: "Entrar al ranking",
    unranked: "Los días anteriores no suman al ranking.",
    guestPlay: "Jugás como invitado: tu puntaje no entra al ranking.",
  },
};

type Copy = typeof es;

const en: Copy = {
  brandA: "What",
  brandB: "Minute?",
  pageName: "Guess the Minute of the Goal",
  round: (n, total) => `Goal ${n} / ${total}`,
  withData: "With data",
  score: "Your points",
  scoredBy: "Goal by",
  goalOf: (a, b) => `Made it ${a}-${b}`,
  penalty: "penalty",
  aet: "Extra time",
  leg: { 1: "1st leg", 2: "2nd leg" },
  stages: { final: "Final", third: "Third place", semi: "Semi-final", quarter: "Quarter-final", r16: "Round of 16", r32: "Round of 32", group: "Group stage", playoff: "Play-off", other: "" },
  group: (g) => `Group ${g}`,
  comps: { FIWC: "World Cup", EURO: "Euro", COPA: "Copa América", CL: "Champions League", EL: "Europa League", CLI: "Libertadores", KLUB: "Club World Cup", USC: "UEFA Super Cup" },
  inputLabel: "What minute was it?",
  minuteBox: "Minute",
  seatScore: (name: string, points: number) => `${name}: ${points} ${points === 1 ? "point" : "points"}`,
  inputPlaceholder: "Minute",
  inputHint: "Added time: 45+2 → type 47",
  invalidMinute: "Type a minute between 1 and 130.",
  confirm: "Confirm",
  exact: "Exact minute! +3",
  off: (diff, points) => `${diff === 1 ? "1 minute" : `${diff} minutes`} off${points > 0 ? ` · +${points}` : ""}`,
  was: (minute) => `It was ${minute}`,
  yourGuess: (minute) => `You said ${minute}`,
  next: "Next goal",
  finish: "See result",
  photo: "Photo",
  intro: {
    lines: [
      "10 famous goals a day: guess the minute each one went in.",
      "Exact minute: 3 points. Within 2 minutes: 2. Within 5: 1.",
      "Added time counts on: a goal at 90+3 is minute 93.",
    ],
    start: "Play",
    resume: (n) => `Continue · goal ${n}`,
    past: "Previous days",
    newBoard: "10 new goals every day at 00:00 (Argentina time).",
    soon: "The first goals are coming soon.",
  },
  end: {
    score: "Points",
    of: (max) => `of ${max}`,
    exact: "Exact",
    avgOff: "Average miss",
    minutes: (n) => `${n} min`,
    streak: "Streak",
    days: (n) => (n === 1 ? "1 day" : `${n} days`),
    comeBack: "10 new goals tomorrow.",
    share: "Share",
    whatsapp: "WhatsApp",
    copy: "Copy",
    copied: "Copied!",
    past: "Play previous days",
    more: "More games",
    answers: "The goals",
    you: "You",
  },
  archive: { title: "Previous days", played: (s) => `${s} pts`, inProgress: "In progress", notPlayed: "Not played", today: "Today", back: "Back" },
  shareText: (n, score, grid, url) => `What Minute? #${n} — ${score}/30\n${grid}\nCan you beat me? ${url}`,
  report: "Report a mistake in this goal",
  reported: "Thanks! We'll check it.",
  exit: "Exit",
  loading: "Loading the goals…",
  loadError: "We couldn't load the goals. Try again in a bit.",
  retry: "Retry",
  actionError: "The connection dropped. Try again.",
  restarted: "Your game changed (another device or a correction). We reloaded it.",
  dayOver: "The day ended in Argentina: the new goals are out.",
  guestYesterday: "You're playing a previous day's goals. Create your account to play today's and join the ranking.",
  playToday: "Play today's",
  maintenance: "The game is under maintenance. Come back in a bit.",
  sessionChanged: "Your session changed. Start again.",
  board: {
    title: "Today's ranking",
    players: (n) => (n === 1 ? "1 player finished" : `${n} players finished`),
    empty: "Nobody has finished today's goals yet. Be the first!",
    rank: (r) => `Rank #${r}`,
    join: "Create your account to join today's ranking",
    joinButton: "Join the ranking",
    unranked: "Previous days don't count for the ranking.",
    guestPlay: "You're playing as a guest: your score isn't ranked.",
  },
};

const ka: Copy = {
  brandA: "რომელ",
  brandB: "წუთზე?",
  pageName: "გამოიცანი გოლის წუთი",
  round: (n, total) => `გოლი ${n} / ${total}`,
  withData: "მონაცემებით",
  score: "შენი ქულები",
  scoredBy: "გოლი:",
  goalOf: (a, b) => `${a}-${b}`,
  penalty: "პენალტი",
  aet: "დამატებითი დრო",
  leg: { 1: "პირველი მატჩი", 2: "საპასუხო მატჩი" },
  stages: { final: "ფინალი", third: "მესამე ადგილი", semi: "ნახევარფინალი", quarter: "მეოთხედფინალი", r16: "1/8 ფინალი", r32: "1/16 ფინალი", group: "ჯგუფური ეტაპი", playoff: "პლეი-ოფი", other: "" },
  group: (g) => `ჯგუფი ${g}`,
  comps: { FIWC: "მსოფლიო ჩემპიონატი", EURO: "ევრო", COPA: "კოპა ამერიკა", CL: "ჩემპიონთა ლიგა", EL: "ევროპის ლიგა", CLI: "ლიბერტადორესი", KLUB: "საკლუბო მსოფლიო თასი", USC: "უეფას სუპერთასი" },
  inputLabel: "რომელ წუთზე გავიდა?",
  minuteBox: "წუთი",
  seatScore: (name: string, points: number) => `${name}: ${points} ქულა`,
  inputPlaceholder: "წუთი",
  inputHint: "დამატებითი დრო: 45+2 → ჩაწერე 47",
  invalidMinute: "ჩაწერე წუთი 1-დან 130-მდე.",
  confirm: "დადასტურება",
  exact: "ზუსტი წუთი! +3",
  off: (diff, points) => `${diff} წუთით შორს${points > 0 ? ` · +${points}` : ""}`,
  was: (minute) => `იყო ${minute}`,
  yourGuess: (minute) => `შენი პასუხი: ${minute}`,
  next: "შემდეგი გოლი",
  finish: "შედეგის ნახვა",
  photo: "ფოტო",
  intro: {
    lines: [
      "დღეში 10 ცნობილი გოლი: გამოიცანი, რომელ წუთზე გავიდა თითოეული.",
      "ზუსტი წუთი: 3 ქულა. 2 წუთის სიზუსტით: 2. 5 წუთის სიზუსტით: 1.",
      "დამატებითი დრო ემატება: 90+3 წუთზე გატანილი გოლი არის 93-ე წუთი.",
    ],
    start: "თამაში",
    resume: (n) => `გაგრძელება · გოლი ${n}`,
    past: "წინა დღეები",
    newBoard: "10 ახალი გოლი ყოველდღე 00:00-ზე (არგენტინის დროით).",
    soon: "პირველი გოლები მალე გამოჩნდება.",
  },
  end: {
    score: "ქულები",
    of: (max) => `${max}-დან`,
    exact: "ზუსტი",
    avgOff: "საშუალო ცდომილება",
    minutes: (n) => `${n} წთ`,
    streak: "სერია",
    days: (n) => `${n} დღე`,
    comeBack: "ხვალ 10 ახალი გოლია.",
    share: "გაზიარება",
    whatsapp: "WhatsApp",
    copy: "კოპირება",
    copied: "დაკოპირდა!",
    past: "წინა დღეების თამაში",
    more: "სხვა თამაშები",
    answers: "გოლები",
    you: "შენ",
  },
  archive: { title: "წინა დღეები", played: (s) => `${s} ქულა`, inProgress: "მიმდინარე", notPlayed: "არ გითამაშია", today: "დღეს", back: "უკან" },
  shareText: (n, score, grid, url) => `რომელ წუთზე? #${n} — ${score}/30\n${grid}\nშეძლებ მეტს? ${url}`,
  report: "შეცდომის შეტყობინება ამ გოლზე",
  reported: "მადლობა! გადავამოწმებთ.",
  exit: "გასვლა",
  loading: "გოლები იტვირთება…",
  loadError: "გოლები ვერ ჩაიტვირთა. სცადე ცოტა ხანში.",
  retry: "თავიდან ცდა",
  actionError: "კავშირი გაწყდა. სცადე თავიდან.",
  restarted: "შენი თამაში შეიცვალა (სხვა მოწყობილობა ან შესწორება). თავიდან ჩავტვირთეთ.",
  dayOver: "არგენტინაში დღე დასრულდა: ახალი გოლები უკვე გამოჩნდა.",
  guestYesterday: "წინა დღის გოლებს თამაშობ. შექმენი ანგარიში, რომ დღევანდელი ითამაშო და რეიტინგში მოხვდე.",
  playToday: "დღევანდელის თამაში",
  maintenance: "თამაში ტექნიკურ სამუშაოებზეა. დაბრუნდი ცოტა ხანში.",
  sessionChanged: "სესია შეიცვალა. დაიწყე თავიდან.",
  board: {
    title: "დღის რეიტინგი",
    players: (n) => `${n} მოთამაშემ დაასრულა`,
    empty: "დღევანდელი გოლები ჯერ არავის დაუსრულებია. იყავი პირველი!",
    rank: (r) => `ადგილი #${r}`,
    join: "შექმენი ანგარიში დღის რეიტინგში მოსახვედრად",
    joinButton: "რეიტინგში შესვლა",
    unranked: "წინა დღეები რეიტინგში არ ითვლება.",
    guestPlay: "სტუმრად თამაშობ: შენი ქულა რეიტინგში არ ითვლება.",
  },
};

const tr: Copy = {
  brandA: "Kaçıncı",
  brandB: "Dakika?",
  pageName: "Gol Dakikası Tahmin Oyunu",
  round: (n, total) => `Gol ${n} / ${total}`,
  withData: "Maç bilgileriyle",
  score: "Puanın",
  scoredBy: "Golü atan",
  goalOf: (a, b) => `${a}-${b} yapan gol`,
  penalty: "penaltı",
  aet: "Uzatma",
  leg: { 1: "İlk maç", 2: "Rövanş" },
  stages: { final: "Final", third: "Üçüncülük", semi: "Yarı final", quarter: "Çeyrek final", r16: "Son 16", r32: "Son 32", group: "Grup aşaması", playoff: "Play-off", other: "" },
  group: (g) => `${g} Grubu`,
  comps: { FIWC: "Dünya Kupası", EURO: "EURO", COPA: "Copa América", CL: "Şampiyonlar Ligi", EL: "Avrupa Ligi", CLI: "Libertadores", KLUB: "Kulüpler Dünya Kupası", USC: "UEFA Süper Kupa" },
  inputLabel: "Gol kaçıncı dakikada?",
  minuteBox: "Dakika",
  seatScore: (name: string, points: number) => `${name}: ${points} puan`,
  inputPlaceholder: "Dakika",
  inputHint: "Uzatma: 45+2 → 47 yaz",
  invalidMinute: "1 ile 130 arasında bir dakika yaz.",
  confirm: "Onayla",
  exact: "Tam dakika! +3",
  off: (diff, points) => `${diff} dakika fark${points > 0 ? ` · +${points}` : ""}`,
  was: (minute) => `Gol ${minute} dakikada`,
  yourGuess: (minute) => `Senin tahminin: ${minute}`,
  next: "Sıradaki gol",
  finish: "Sonucu gör",
  photo: "Fotoğraf",
  intro: {
    lines: [
      "Her gün 10 ünlü gol: her birinin kaçıncı dakikada atıldığını tahmin et.",
      "Tam dakika: 3 puan. En fazla 2 dakika fark: 2. En fazla 5 dakika fark: 1.",
      "Uzatma eklenir: 90+3'te atılan gol 93. dakikadır.",
    ],
    start: "Oyna",
    resume: (n) => `Devam et · gol ${n}`,
    past: "Önceki günler",
    newBoard: "Her gün 00:00'da 10 yeni gol (Arjantin saati).",
    soon: "İlk goller çok yakında.",
  },
  end: {
    score: "Puan",
    of: (max) => `/ ${max}`,
    exact: "Tam isabet",
    avgOff: "Ortalama fark",
    minutes: (n) => `${n} dk`,
    streak: "Seri",
    days: (n) => `${n} gün`,
    comeBack: "Yarın 10 yeni gol var.",
    share: "Paylaş",
    whatsapp: "WhatsApp",
    copy: "Kopyala",
    copied: "Kopyalandı!",
    past: "Önceki günleri oyna",
    more: "Diğer oyunlar",
    answers: "Goller",
    you: "Sen",
  },
  archive: { title: "Önceki günler", played: (s) => `${s} puan`, inProgress: "Devam ediyor", notPlayed: "Oynanmadı", today: "Bugün", back: "Geri" },
  shareText: (n, score, grid, url) => `Kaçıncı Dakika? #${n} — ${score}/30\n${grid}\nBeni geçebilir misin? ${url}`,
  report: "Bu golde bir hata bildir",
  reported: "Teşekkürler! İnceleyeceğiz.",
  exit: "Çık",
  loading: "Goller yükleniyor…",
  loadError: "Goller yüklenemedi. Biraz sonra tekrar dene.",
  retry: "Tekrar dene",
  actionError: "Bağlantı koptu. Tekrar dene.",
  restarted: "Oyunun değişti (başka cihaz ya da düzeltme). Yeniden yükledik.",
  dayOver: "Arjantin'de gün bitti: yeni goller geldi.",
  guestYesterday: "Önceki bir günün gollerini oynuyorsun. Bugünkünü oynamak ve sıralamaya girmek için hesap oluştur.",
  playToday: "Bugünkünü oyna",
  maintenance: "Oyun bakımda. Biraz sonra tekrar gel.",
  sessionChanged: "Oturumun değişti. Baştan başla.",
  board: {
    title: "Günün sıralaması",
    players: (n) => `${n} oyuncu bitirdi`,
    empty: "Bugünün gollerini henüz kimse bitirmedi. İlk sen ol!",
    rank: (r) => `Sıra #${r}`,
    join: "Günün sıralamasına girmek için hesap oluştur",
    joinButton: "Sıralamaya gir",
    unranked: "Önceki günler sıralamaya sayılmaz.",
    guestPlay: "Misafir olarak oynuyorsun: puanın sıralamaya girmez.",
  },
};

const COPY: Record<string, Copy> = { es, en, ka, tr };

export const minutoCopy = (locale: string): Copy => COPY[locale] ?? en;

export const nameFor = (name: LocalizedName, locale: string): string => name[(locale as MinutoLocale)] ?? name.en;
