"""Frozen Squad Spin combos for the sneak peek: reels (with labels/assets), valid answers and their aliases.
Usage: python3 scripts/gen-squad-spin-sample.py <file-with-staging-db-url>"""
import json, pathlib, subprocess, sys
SDB = open(sys.argv[1]).read().strip()
PER_TIER = {"t3e": 10, "t3m": 6}
# Players whose staging record shows a Georgian name the aliases do not accept (Douglas Luiz) or the wrong person (Alan → Shearer);
# fix the rows, then drop them from here.
EXCLUDED = ",".join(f"'{i}'" for i in ("f50c01d5-e1b4-4b1f-b2a2-bad72af78dc4", "ea3660e1-ff91-4c47-b1b3-0c2edf74ab38"))
POSITION_LABELS = {"GK": {"en": "Goalkeeper", "ka": "მეკარე"}, "DEF": {"en": "Defender", "ka": "მცველი"}, "MID": {"en": "Midfielder", "ka": "ნახევარმცველი"}, "FWD": {"en": "Forward", "ka": "თავდამსხმელი"}}
def q(sql):
    out = subprocess.run(['psql', SDB, '-Atc', sql], capture_output=True, text=True)
    if out.returncode != 0: raise SystemExit(out.stderr)
    return [json.loads(l) for l in out.stdout.split('\n') if l.strip()]
combos = []
for tier, n in PER_TIER.items():
    rows = q(f"""select json_build_object('id', c.id, 'reels', c.reels, 'tier', c.tier, 'position_group', c.position_group,
        'criteria', (select json_agg(json_build_object('id', k.id, 'family', k.family, 'key', k.criterion_key, 'label_en', k.label_en, 'label_ka', k.label_ka, 'asset_key', k.asset_key) order by array_position(array[c.club_id, c.nation_id] || c.extra_ids, k.id))
                     from squad_spin_criteria k where k.id = any(array[c.club_id, c.nation_id] || c.extra_ids)),
        'answers', (select json_agg(json_build_object('id', p.id, 'name_en', p.name_en, 'name_ka', p.name_ka, 'image_url', null)) from squad_spin_players p where p.id = any(c.answer_ids)),
        'aliases', (select json_agg(json_build_object('player_id', a.player_id, 'alias', a.normalized_alias, 'locale', a.locale, 'policy', a.acceptance_policy)) from squad_spin_player_aliases a where a.player_id = any(c.answer_ids)))::text
        from squad_spin_combos c where c.active and c.tier='{tier}' and c.n_answers between 2 and 12
          and not (c.answer_ids && array[{EXCLUDED}]::uuid[])
        order by md5(c.id::text || 'coin-sample-v1') limit {n}""")
    for d in rows:
        crit = {k['id']: k for k in d['criteria']}
        # reel order like the live service: club, position, nation, extras
        ids = [k['id'] for k in d['criteria']]
        club = next(k for k in d['criteria'] if k['family'] == 'club'); nation = next(k for k in d['criteria'] if k['family'] == 'country')
        extras = [k for k in d['criteria'] if k['id'] not in (club['id'], nation['id'])]
        pos = d['position_group']
        reels = [club, {'family': 'position', 'id': pos, 'key': pos, 'label_en': POSITION_LABELS[pos]['en'], 'label_ka': POSITION_LABELS[pos]['ka'], 'asset_key': None}, nation, *extras]
        combos.append({'id': d['id'], 'tier': d['tier'], 'reels': reels, 'answers': d['answers'], 'aliases': d['aliases'] or []})
out = pathlib.Path(__file__).resolve().parent.parent / 'src/features/coin-samples/data/sampleSquadSpin.ts'
out.write_text('// GENERATED by scripts/gen-squad-spin-sample.py from the staging Squad Spin content — fixed combos\n// for the sneak peek with their reels, valid answers and reviewed aliases. Regenerate rather than editing by hand.\n'
               'import type { SampleSquadSpinCombo } from "../types";\n\nexport const SAMPLE_SQUAD_SPIN_COMBOS: SampleSquadSpinCombo[] = ' + json.dumps(combos, ensure_ascii=False, indent=2) + ';\n')
print('combos written:', {t: sum(1 for c in combos if c['tier'] == t) for t in PER_TIER}, 'aliases', sum(len(c['aliases']) for c in combos))
