"""Frozen MCQ bank for the coin-game sneak peeks (Trivia Mines, Free Kicks, Road to Goal).
Usage: python3 scripts/gen-coin-sample-questions.py <file-with-staging-db-url>
Picks published mcq_single questions that carry all four locales and no image, a fixed count per
difficulty, ordered by a stable hash so the bank is the same on every run until the pool changes."""
import json, pathlib, subprocess, sys
SDB = open(sys.argv[1]).read().strip()
PER_DIFFICULTY = {"easy": 24, "medium": 24, "hard": 12}
def q(sql):
    out = subprocess.run(['psql', SDB, '-Atc', sql], capture_output=True, text=True)
    if out.returncode != 0: raise SystemExit(out.stderr)
    return [l for l in out.stdout.split('\n') if l.strip()]
bank = []
for difficulty, n in PER_DIFFICULTY.items():
    rows = q(f"""select json_build_object('id', q.id, 'difficulty', q.difficulty, 'category', c.name, 'prompt', q.prompt, 'options', p.payload->'options')::text
        from questions q join question_payloads p on p.question_id=q.id left join categories c on c.id=q.category_id
        where q.type='mcq_single' and q.status='published' and q.difficulty='{difficulty}'
          and q.prompt ? 'en' and q.prompt ? 'ka' and q.prompt ? 'es' and q.prompt ? 'tr' and (p.payload->>'image_url') is null
          and jsonb_array_length(p.payload->'options') = 4
        order by md5(q.id::text || 'coin-sample-v1') limit {n}""")
    for r in rows:
        d = json.loads(r)
        opts = d['options']
        if not all(all(o['text'].get(l) for l in ('en', 'ka', 'es', 'tr')) for o in opts): continue
        correct = [o['id'] for o in opts if o.get('is_correct')]
        if len(correct) != 1: continue
        bank.append({'id': d['id'], 'difficulty': difficulty, 'category': {l: (d['category'] or {}).get(l) or (d['category'] or {}).get('en') or '' for l in ('en', 'ka', 'es', 'tr')},
                     'prompt': {l: d['prompt'][l] for l in ('en', 'ka', 'es', 'tr')},
                     'options': [{'id': o['id'], 'text': {l: o['text'][l] for l in ('en', 'ka', 'es', 'tr')}} for o in opts], 'correctOptionId': correct[0]})
counts = {k: sum(1 for b in bank if b['difficulty'] == k) for k in PER_DIFFICULTY}
out = pathlib.Path(__file__).resolve().parent.parent / 'src/features/coin-samples/data/sampleQuestions.ts'
out.write_text('// GENERATED by scripts/gen-coin-sample-questions.py from the staging question pool — a fixed,\n// four-language MCQ bank for the coin-game sneak peeks. Regenerate rather than editing by hand.\n'
               'import type { SampleQuestion } from "../types";\n\nexport const SAMPLE_QUESTIONS: SampleQuestion[] = ' + json.dumps(bank, ensure_ascii=False, indent=2) + ';\n')
print('bank written:', counts, 'total', len(bank))
