/** All player-facing Table Derby strings. Georgian only — no English may
 *  reach the UI (product rule; see CLAUDE.md design section). */
export const TD = {
  title: 'მაგიდის დერბი',
  titleLine1: 'მაგიდის',
  titleLine2: 'დერბი',
  tagline: 'პირისპირ დუელი · 3 ტური',
  playCta: 'თამაშის დაწყება',
  poweredBy: 'betsson.sport', // brand wordmark, not translatable copy
  poweredByQuizball: 'powered by Quizball', // brand lockup, as on the boot loader


  // Shell (Betsson-style chrome)
  navLabel: 'ნავიგაცია',
  tabHome: 'მთავარი',
  tabDaily: 'ყოველდღიური',
  tabSolo: 'ივარჯიშე',
  tabProfile: 'პროფილი',
  rankedLabel: 'რანკედი',
  rankedRounds: ['ბარათონი', 'გამარჯობა, ჩემი სახელია', 'პაპა კარლო'],
  rankedRules: 'მოგება +25 ქულა · წაგება −10 ქულა · 1 ბილეთი',
  menuSolo: 'ივარჯიშე',
  menuSoloSub: 'სტრიქ ტურნირი · უფასო · ნებისმიერ დროს',
  // Practice — streak tournament (Betsson REQ.1.8–1.10)
  streakTitle: 'სტრიქ ტურნირი',
  streakRules: 'უპასუხე კითხვებს ზედიზედ. ერთი შეცდომა ან ამოწურული დრო — და სერია მთავრდება. რაც უფრო შორს წახვალ, მით უფრო რთულდება.',
  streakRulesTime: (s: number) => `${s} წამი თითო კითხვაზე`,
  streakBest: 'საუკეთესო სერია',
  streakLast: 'ბოლო შედეგი',
  streakStart: 'დაწყება',
  streakCounter: 'სერია',
  streakNext: 'შემდეგი კითხვა',
  streakSeeResult: 'შედეგის ნახვა',
  streakTimeUp: 'დრო ამოიწურა',
  streakExit: 'გასვლა',
  streakOver: 'სერია დასრულდა',
  streakInARow: 'სწორი პასუხი ზედიზედ',
  streakNewRecord: 'ახალი რეკორდი!',
  streakShare: 'გაზიარება',
  streakShared: 'სურათი შენახულია — გააზიარე სოციალურ ქსელში',
  streakAgain: 'თავიდან თამაში',
  streakBack: 'უკან',
  streakShareText: (n: number) => `ჩემი სერია მაგიდის დერბიში — ${n} სწორი პასუხი ზედიზედ! შენ რამდენს მოხსნი?`,
  streakPhotoCredit: 'ფოტო',
  dailySub: 'ყოველდღე ახალი · უფასო',
  dailyOpen: 'ითამაშე',
  lbWeek: 'კვირა',
  lbAllTime: 'სულ',
  lbRankings: 'რეიტინგი',
  lbMonthly: 'თვე',
  lbYou: 'შენ',
  profileTitle: 'პროფილი',
  statsTitle: 'სტატისტიკა',
  statPlayed: 'მატჩი',
  statWins: 'მოგება',
  statWinRate: 'მოგების %',
  statStreak: 'სერია',
  statBestStreak: (n: number) => `საუკეთესო ${n}`,
  statsRankedOnly: 'მხოლოდ რანკედი მატჩები',
  matchesTitle: 'ჩემი მატჩები',
  matchesEmpty: 'ჯერ მატჩი არ გითამაშია — დაიწყე პირველი!',
  matchVs: (name: string) => `vs ${name}`,
  modeRanked: 'რანკედი',
  modeSolo: 'სოლო',
  resultWin: 'მოგება',
  resultLoss: 'წაგება',
  onPenalties: 'პენალტებით',
  profileInfo: 'ინფორმაცია',
  devSeedMatches: 'მატჩების ისტორიის შევსება',
  profileFavClub: 'საყვარელი გუნდი',
  profileChangeClub: 'შეცვლა',
  profileRules: 'თამაშის წესები',
  profilePrivacy: 'უსაფრთხოების პოლიტიკა',
  profileTerms: 'წესები და პირობები',
  logout: 'გასვლა',
  devTools: 'დეველოპერი',
  devResetTickets: 'ბილეთების აღდგენა',
  devReplayOnboarding: 'ონბორდინგის თავიდან ნახვა',
  noTicketsTitle: 'ბილეთები ამოიწურა',
  noTicketsBody: 'დღევანდელი ბილეთები გამოყენებულია. ახალი ბილეთები ხვალ 00:00-ზე დაგერიცხება.',
  noTicketsSolo: 'ივარჯიშე',
  noTicketsRanked: 'რანკედი · 0 ბილეთი',
  noTicketsFoot: 'ბილეთები ყოველდღე განახლდება',
  close: 'დახურვა',
  rpDelta: 'რეიტინგის ქულა',
  rpTotal: 'სულ',
  soloNoRp: 'სოლო · ქულები არ იცვლება',

  // Menu
  menuMatchSub: 'პირისპირ დუელი · 3 ტური',
  menuDaily: 'დღიური გამოწვევები',
  menuDailySub: 'ყოველდღე ახალი გამოწვევა',
  menuDailyNew: 'ახალი',
  menuDailyDone: 'შესრულებულია',
  menuWl: 'უიქენდის ლიგა',
  menuWlSub: 'დააგროვე ქულები და მოხვდი ლიგაში',
  wlJoin: 'შემოგვიერთდი ყოველ შაბათ-კვირას და მოიგე პრიზები',
  wlStartsIn: 'იწყება',
  dailyFl: 'საფეხბურთო ლოგიკა',
  dailyPio: 'დაალაგე სწორად',
  dailyCp: 'კარიერის გზა',
  lbYourRank: 'შენი ადგილი',
  menuLb: 'ლიდერბორდი',
  menuLbSub: 'საუკეთესო მოთამაშეები',
  playNow: 'თამაში',
  ticketCost: '1 ბილეთი',
  tickets: 'ბილეთები',
  chooseAvatar: 'აირჩიე ავატარი',
  noTickets: 'ბილეთები აღარ გაქვს — განახლდება ხვალ',
  back: 'უკან',

  // Onboarding (first visit; Betsson passes identity, no auth here)
  onbWelcome: 'მოგესალმები მაგიდის დერბიში!',
  onbAvatarTitle: 'აირჩიე ავატარი',
  onbClubTitle: 'აირჩიე საყვარელი გუნდი',
  onbClubSearch: 'მოძებნე და აირჩიე გუნდი',
  onbNext: 'შემდეგი',
  onbStart: 'დაწყება',

  // Daily
  dailyToday: 'დღევანდელი გამოწვევა',
  dailyYourScore: 'შენი შედეგი',
  dailyComeBack: 'ახალი გამოწვევა ხვალ',
  dailyFinish: 'დასრულება',
  dailyRewardTicket: '+1 ბილეთი',
  dailyStart: 'დაწყება',
  dailyRulesFl: 'ორი კლუბი და ერთი მინიშნება — გამოიცანი ფეხბურთელი, რომელიც მათ აკავშირებს. 10 კითხვა, თითოეულზე 25 წამი; რაც უფრო სწრაფად უპასუხებ, მეტ ქულას მიიღებ.',
  dailyRulesPio: 'გადაათრიე ბარათები და დაალაგე სწორი თანმიმდევრობით. თითო რაუნდზე 45 წამი გაქვს — დრო რომ ამოიწუროს, პასუხი ავტომატურად ჩაითვლება.',
  dailyRulesCp: 'ფეხბურთელის კარიერის კლუბები სათითაოდ იხსნება. ჩაწერე ვინ არის, რაც შეიძლება ადრე — ნაკლები კლუბი ნიშნავს მეტ ქულას.',
  dailyPillFl: 'სწორი პასუხი · 100 — ბოლო წამზე · 40',
  dailyPillPio: 'ყოველი სწორი პოზიცია · +25',
  dailyPillCp: 'ადრეული პასუხი · 100 — ბოლო კლუბზე · 20',
  confirmOrder: 'დადასტურება',

  // Weekend League
  wlQpLabel: 'საკვალიფიკაციო ქულები',
  wlHowTo: 'ითამაშე მაგიდის დერბი და დააგროვე ქულები',
  wlWin: 'მოგება: +25 ქულა',
  wlLoss: 'წაგება: +10 ქულა',
  wlSchedule: 'ლიგა იწყება ყოველ შაბათს',
  wlPrizes: 'პრიზები Betsson.sport-ისგან',
  wlQualified: 'კვალიფიკაცია მიღებულია!',
  wlEnterSoon: 'ლიგაში შესვლა · მალე',
  qpEarned: 'საკვალიფიკაციო ქულა',
  qpShort: 'ქულა',

  // Leaderboard
  lbWeekly: 'კვირის რეიტინგი',

  // Matchmaking
  searching: 'მოწინააღმდეგის ძებნა',
  found: 'მოწინააღმდეგე ნაპოვნია!',
  you: 'შენ',

  // Showdown
  bestOfRounds: '3 ტური · 1 + 1 + 2 ქულა',

  // RPS
  rpsTitle: 'ვინ დაიწყებს?',
  rpsSubtitle: 'ქვა · ქაღალდი · მაკრატელი',
  rpsRock: 'ქვა',
  rpsPaper: 'ქაღალდი',
  rpsScissors: 'მაკრატელი',
  rpsTie: 'ფრე! კიდევ ერთხელ',
  rpsYouStart: 'შენ იწყებ!',
  rpsOpponentStarts: 'იწყებს მოწინააღმდეგე',

  // Match
  roundLabel: 'ტური',
  yourTurn: 'შენი ჯერია — ჩაწერე პასუხი',
  opponentTurn: 'ფიქრობს...',
  answerPlaceholder: 'ჩაწერე პასუხი...',
  submit: 'პასუხი',
  correct: 'სწორია!',
  wrong: 'არასწორია',
  duplicate: 'ეს პასუხი უკვე დასახელდა',
  timeUp: 'დრო ამოიწურა',

  // Round 2 — ბარათონი
  roundCardsName: 'ბარათონი',
  roundBuzzerName: 'გამარჯობა, ჩემი სახელია',
  roundWorth: (n: number) => `ტურის მოგება · ${n} ქულა`,
  pointsYou: (n: number) => `+${n} ქულა შენ`,
  pointsOpponent: (n: number) => `+${n} ქულა მეტოქეს`,
  pickCard: 'აირჩიე ბარათი',
  opponentPicking: 'ირჩევს ბარათს...',
  stealChance: 'მოპარვის შანსი!',
  opponentStealing: 'ცდილობს მოპარვას...',
  roundDecided: 'ტური გადაწყდა',

  // Round 3 — პაპა კარლოს ყუთი
  round3Name: 'პაპა კარლოს ყუთი',
  rollBox: 'დაატრიალე ყუთი და აირჩიე კატეგორია',
  opponentChoosing: 'ირჩევს კატეგორიას...',
  questionsLeftSuffix: 'კითხვა',

  // Round 4 — ვინ ვარ მე? (buzzer)
  buzz: 'ვიცი!',
  buzzRules: 'ვინც პირველი დააჭერს — ის პასუხობს',
  youBuzzed: 'უპასუხე!',
  opponentBuzzed: 'დააჭირა!',
  lockedOut: 'ამ კითხვაზე ვეღარ უპასუხებ',
  answerWas: 'პასუხი:',

  // Penalties
  penaltiesName: 'პენალტები',
  penaltiesIntro: '10 შეკითხვა · ვინც პირველი დააჭერს — ის პასუხობს · მინუსი არ არის',
  suddenDeath: 'გადამწყვეტი შეკითხვა!',

  // Round end / results
  roundWon: 'ტური შენია!',
  roundLost: 'ტური წააგე',
  roundTie: 'ფრე ტურში',
  matchScore: 'ანგარიში',
  nextRound: 'შემდეგი ტური',
  seeResults: 'შედეგები',
  matchWon: 'მატჩი შენია!',
  matchLost: 'მატჩი წააგე',
  resultsTitle: 'მატჩის შედეგი',
  nextRoundsSoon: 'შემდეგი რაუნდები მალე დაემატება',
  playAgain: 'თავიდან თამაში',
  backHome: 'მთავარზე დაბრუნება',
} as const;

/** Mock opponent display names (Georgian). */
export const OPPONENT_NAMES = [
  'გიორგი მ.',
  'ნიკა კ.',
  'ლუკა წ.',
  'სანდრო ბ.',
  'დათო ხ.',
  'თორნიკე გ.',
] as const;
