import type { Difficulty } from "./buscaminas.logic";

const es = {
  brandA: "Buscaminas",
  brandB: "futbolero",
  round: (n: number, total: number) => `Ronda ${n} / ${total}`,
  difficulty: { easy: "Fácil", medium: "Media", hard: "Difícil" } satisfies Record<Difficulty, string>,
  found: "Aciertos",
  pot: "Pozo",
  points: "pts",
  bank: (n: number) => `Plantarme · +${n}`,
  bankHint: "Encontrá al menos uno para plantarte",
  next: "Siguiente ronda",
  finish: "Ver resultado",
  perfect: (n: number) => `¡Ronda perfecta! +${n}`,
  banked: (n: number) => `Te plantaste: +${n}`,
  mine: (lost: number) => (lost > 1 ? `¡Mina! Perdiste los ${lost} puntos de esta ronda` : lost === 1 ? "¡Mina! Perdiste el punto de esta ronda" : "¡Mina!"),
  mineCard: "Mina",
  fitCard: "Cumplía la consigna",
  revealLater: "Las respuestas de hoy se ven mañana en «Días anteriores».",
  tooManyRuns: "Llegaste al máximo de partidas de hoy como invitado. Creá tu cuenta para seguir jugando y entrar al ranking.",
  intro: {
    title: (n: number) => `Buscaminas futbolero #${n}`,
    lines: [
      "20 rondas que se ponen cada vez más difíciles.",
      "Cada ronda tiene 16 jugadores: 12 cumplen la consigna y 4 son minas.",
      "Tocá a los que cumplen. Si tocás una mina, perdés los puntos de esa ronda.",
      "Plantate cuando quieras para guardar tus aciertos. Los 12 dan +3 de bonus.",
    ],
    start: "Jugar",
    resume: (n: number) => `Seguir · ronda ${n}`,
    past: "Días anteriores",
    newBoard: "Un tablero nuevo cada día a las 00:00 (hora de Argentina).",
  },
  end: {
    title: (n: number) => `Buscaminas futbolero #${n}`,
    score: "Puntos",
    of: (max: number) => `de ${max}`,
    perfects: "Rondas perfectas",
    mines: "Minas pisadas",
    streak: "Racha",
    days: (n: number) => (n === 1 ? "1 día" : `${n} días`),
    comeBack: "Mañana hay tablero nuevo.",
    share: "Compartir resultado",
    whatsapp: "WhatsApp",
    copy: "Copiar",
    copied: "¡Copiado!",
    past: "Jugar días anteriores",
    signup: "Creá tu cuenta y jugá todos los juegos de QuizBall",
    signupButton: "Crear cuenta",
    more: "Más juegos",
    trivia: "Minas de trivia",
    grid: "Tic Tac Toe futbolero",
  },
  archive: { title: "Días anteriores", played: (s: number) => `${s} pts`, inProgress: "En curso", notPlayed: "Sin jugar", today: "Hoy", back: "Volver" },
  shareText: (n: number, score: number, grid: string, url: string) => `Buscaminas futbolero #${n} — ${score} pts\n${grid}\n¿Me superás? ${url}`,
  report: "Reportar un error",
  reported: "¡Gracias! Lo revisamos.",
  exit: "Salir",
  loading: "Cargando el tablero…",
  loadError: "No pudimos cargar el tablero. Probá de nuevo en un rato.",
  retry: "Reintentar",
  actionError: "Se cortó la conexión. Probá de nuevo.",
  restarted: "Tu partida cambió (otro dispositivo o una corrección). La recargamos.",
  dayOver: "Terminó el día en Argentina: ya está el tablero nuevo.",
  guestYesterday: "Estás jugando el tablero de ayer. Creá tu cuenta para jugar el de hoy y entrar al ranking.",
  playToday: "Jugar el de hoy",
  maintenance: "El juego está en mantenimiento. Volvé en un rato.",
  sessionChanged: "Cambió tu sesión. Arrancá de nuevo el tablero.",
  board: {
    title: "Ranking del día",
    players: (n: number) => (n === 1 ? "1 jugador terminó" : `${n} jugadores terminaron`),
    empty: "Todavía nadie terminó el tablero de hoy. ¡Sé el primero!",
    you: "Vos",
    rank: (r: number) => `Puesto #${r}`,
    join: "Creá tu cuenta para entrar al ranking del día",
    joinButton: "Entrar al ranking",
    unranked: "Los días anteriores no suman al ranking.",
    guestPlay: "Jugás como invitado: tu puntaje no entra al ranking.",
  },
};

type Copy = typeof es;

const en: Copy = {
  brandA: "Football",
  brandB: "Minesweeper",
  round: (n, total) => `Round ${n} / ${total}`,
  difficulty: { easy: "Easy", medium: "Medium", hard: "Hard" },
  found: "Found",
  pot: "Pot",
  points: "pts",
  bank: (n) => `Bank · +${n}`,
  bankHint: "Find at least one to bank",
  next: "Next round",
  finish: "See result",
  perfect: (n) => `Perfect round! +${n}`,
  banked: (n) => `Banked: +${n}`,
  mine: (lost) => (lost > 1 ? `Mine! You lost this round's ${lost} points` : lost === 1 ? "Mine! You lost this round's point" : "Mine!"),
  mineCard: "Mine",
  fitCard: "Fit the clue",
  revealLater: "Today's answers show up tomorrow in “Previous days”.",
  tooManyRuns: "You've reached today's guest limit. Create an account to keep playing and get ranked.",
  intro: {
    title: (n) => `Football Minesweeper #${n}`,
    lines: [
      "20 rounds that get harder as you go.",
      "Each round shows 16 players: 12 fit the clue and 4 are mines.",
      "Tap the ones that fit. Hit a mine and you lose that round's points.",
      "Bank whenever you like to keep your hits. All 12 earn a +3 bonus.",
    ],
    start: "Play",
    resume: (n) => `Continue · round ${n}`,
    past: "Previous days",
    newBoard: "A new board every day at midnight (Argentina time).",
  },
  end: {
    title: (n) => `Football Minesweeper #${n}`,
    score: "Points",
    of: (max) => `of ${max}`,
    perfects: "Perfect rounds",
    mines: "Mines hit",
    streak: "Streak",
    days: (n) => (n === 1 ? "1 day" : `${n} days`),
    comeBack: "New board tomorrow.",
    share: "Share result",
    whatsapp: "WhatsApp",
    copy: "Copy",
    copied: "Copied!",
    past: "Play previous days",
    signup: "Create an account and play every QuizBall game",
    signupButton: "Sign up",
    more: "More games",
    trivia: "Trivia Mines",
    grid: "Football Tic Tac Toe",
  },
  archive: { title: "Previous days", played: (s) => `${s} pts`, inProgress: "In progress", notPlayed: "Not played", today: "Today", back: "Back" },
  shareText: (n, score, grid, url) => `Football Minesweeper #${n} — ${score} pts\n${grid}\nCan you beat me? ${url}`,
  report: "Report a mistake",
  reported: "Thanks! We'll check it.",
  exit: "Exit",
  loading: "Loading the board…",
  loadError: "We couldn't load the board. Try again in a moment.",
  retry: "Retry",
  actionError: "Connection lost. Try again.",
  restarted: "Your run changed (another device or a correction). We reloaded it.",
  dayOver: "The day ended in Argentina: the new board is ready.",
  guestYesterday: "You're playing yesterday's board. Create an account to play today's and get ranked.",
  playToday: "Play today's board",
  maintenance: "The game is under maintenance. Please come back soon.",
  sessionChanged: "Your session changed. Start the board again.",
  board: {
    title: "Today's leaderboard",
    players: (n) => (n === 1 ? "1 player finished" : `${n} players finished`),
    empty: "Nobody has finished today's board yet. Be the first!",
    you: "You",
    rank: (r) => `Rank #${r}`,
    join: "Create an account to get on today's leaderboard",
    joinButton: "Join the leaderboard",
    unranked: "Previous days don't count for the leaderboard.",
    guestPlay: "You're playing as a guest: your score isn't ranked.",
  },
};

const ka: Copy = {
  brandA: "საფეხბურთო",
  brandB: "მაღაროები",
  round: (n, total) => `რაუნდი ${n} / ${total}`,
  difficulty: { easy: "მარტივი", medium: "საშუალო", hard: "რთული" },
  found: "სწორი",
  pot: "ბანკი",
  points: "ქულა",
  bank: (n) => `შენახვა · +${n}`,
  bankHint: "შესანახად ერთი სწორი მაინც იპოვე",
  next: "შემდეგი რაუნდი",
  finish: "შედეგის ნახვა",
  perfect: (n) => `იდეალური რაუნდი! +${n}`,
  banked: (n) => `შენახულია: +${n}`,
  mine: (lost) => (lost > 0 ? `მაღარო! ამ რაუნდის ${lost} ქულა დაიკარგა` : "მაღარო!"),
  mineCard: "მაღარო",
  fitCard: "პირობას აკმაყოფილებდა",
  revealLater: "დღევანდელი პასუხები ხვალ გამოჩნდება „წინა დღეებში“.",
  tooManyRuns: "სტუმრად დღევანდელი თამაშების ლიმიტს მიაღწიე. შექმენი ანგარიში, რომ გააგრძელო და რეიტინგში მოხვდე.",
  intro: {
    title: (n) => `საფეხბურთო მაღაროები #${n}`,
    lines: [
      "20 რაუნდი, რომლებიც თანდათან რთულდება.",
      "ყოველ რაუნდში 16 მოთამაშეა: 12 პირობას აკმაყოფილებს, 4 მაღაროა.",
      "დააჭირე მათ, ვინც შეესაბამება. მაღაროზე დაჭერით რაუნდის ქულებს კარგავ.",
      "შეინახე ქულები ნებისმიერ დროს. 12-ვე სწორი +3 ბონუსს იძლევა.",
    ],
    start: "თამაში",
    resume: (n) => `გაგრძელება · რაუნდი ${n}`,
    past: "წინა დღეები",
    newBoard: "ახალი დაფა ყოველდღე შუაღამისას (არგენტინის დროით).",
  },
  end: {
    title: (n) => `საფეხბურთო მაღაროები #${n}`,
    score: "ქულა",
    of: (max) => `${max}-დან`,
    perfects: "იდეალური რაუნდები",
    mines: "მაღაროები",
    streak: "სერია",
    days: (n) => `${n} დღე`,
    comeBack: "ხვალ ახალი დაფაა.",
    share: "გაზიარება",
    whatsapp: "WhatsApp",
    copy: "კოპირება",
    copied: "დაკოპირდა!",
    past: "წინა დღეების თამაში",
    signup: "შექმენი ანგარიში და ითამაშე QuizBall-ის ყველა თამაში",
    signupButton: "რეგისტრაცია",
    more: "მეტი თამაში",
    trivia: "ტრივია-მაღაროები",
    grid: "იქს-ნული",
  },
  archive: { title: "წინა დღეები", played: (s) => `${s} ქულა`, inProgress: "მიმდინარეობს", notPlayed: "არ გითამაშია", today: "დღეს", back: "უკან" },
  shareText: (n, score, grid, url) => `საფეხბურთო მაღაროები #${n} — ${score} ქულა\n${grid}\nმაჯობებ? ${url}`,
  report: "შეცდომის შეტყობინება",
  reported: "მადლობა! გადავამოწმებთ.",
  exit: "გასვლა",
  loading: "დაფა იტვირთება…",
  loadError: "დაფა ვერ ჩაიტვირთა. სცადე ცოტა ხანში.",
  retry: "თავიდან ცდა",
  actionError: "კავშირი გაწყდა. სცადე თავიდან.",
  restarted: "შენი თამაში შეიცვალა (სხვა მოწყობილობა ან შესწორება). თავიდან ჩავტვირთეთ.",
  dayOver: "არგენტინაში დღე დასრულდა: ახალი დაფა მზადაა.",
  guestYesterday: "გუშინდელ დაფას თამაშობ. შექმენი ანგარიში, რომ დღევანდელი ითამაშო და რეიტინგში მოხვდე.",
  playToday: "დღევანდელის თამაში",
  maintenance: "თამაში დროებით მიუწვდომელია. ცოტა ხანში დაბრუნდი.",
  sessionChanged: "შენი სესია შეიცვალა. დაფა თავიდან დაიწყე.",
  board: {
    title: "დღის რეიტინგი",
    players: (n) => `${n} მოთამაშემ დაასრულა`,
    empty: "დღევანდელი დაფა ჯერ არავის დაუსრულებია. იყავი პირველი!",
    you: "შენ",
    rank: (r) => `ადგილი #${r}`,
    join: "შექმენი ანგარიში და მოხვდი დღის რეიტინგში",
    joinButton: "რეიტინგში შესვლა",
    unranked: "წინა დღეები რეიტინგში არ ითვლება.",
    guestPlay: "სტუმრად თამაშობ: შენი ქულა რეიტინგში არ ითვლება.",
  },
};

const tr: Copy = {
  brandA: "Futbol",
  brandB: "Mayın Tarlası",
  round: (n, total) => `Tur ${n} / ${total}`,
  difficulty: { easy: "Kolay", medium: "Orta", hard: "Zor" },
  found: "Doğru",
  pot: "Kasa",
  points: "puan",
  bank: (n) => `Kasaya al · +${n}`,
  bankHint: "Kasaya almak için en az bir doğru bul",
  next: "Sonraki tur",
  finish: "Sonucu gör",
  perfect: (n) => `Mükemmel tur! +${n}`,
  banked: (n) => `Kasaya alındı: +${n}`,
  mine: (lost) => (lost > 0 ? `Mayın! Bu turun ${lost} puanı gitti` : "Mayın!"),
  mineCard: "Mayın",
  fitCard: "İpucuna uyuyordu",
  revealLater: "Bugünün cevapları yarın “Önceki günler” bölümünde görünür.",
  tooManyRuns: "Bugünkü misafir sınırına ulaştın. Oynamaya devam etmek ve sıralamaya girmek için hesap oluştur.",
  intro: {
    title: (n) => `Futbol Mayın Tarlası #${n}`,
    lines: [
      "Giderek zorlaşan 20 tur.",
      "Her turda 16 oyuncu var: 12'si ipucuna uyar, 4'ü mayın.",
      "Uyanlara dokun. Mayına basarsan o turun puanlarını kaybedersin.",
      "İstediğin an kasaya al. 12'sini de bulursan +3 bonus.",
    ],
    start: "Oyna",
    resume: (n) => `Devam et · tur ${n}`,
    past: "Önceki günler",
    newBoard: "Her gün gece yarısı yeni tahta (Arjantin saati).",
  },
  end: {
    title: (n) => `Futbol Mayın Tarlası #${n}`,
    score: "Puan",
    of: (max) => `/ ${max}`,
    perfects: "Mükemmel turlar",
    mines: "Basılan mayınlar",
    streak: "Seri",
    days: (n) => `${n} gün`,
    comeBack: "Yarın yeni tahta var.",
    share: "Paylaş",
    whatsapp: "WhatsApp",
    copy: "Kopyala",
    copied: "Kopyalandı!",
    past: "Önceki günleri oyna",
    signup: "Hesap oluştur, QuizBall'daki tüm oyunları oyna",
    signupButton: "Kaydol",
    more: "Daha fazla oyun",
    trivia: "Bilgi Mayınları",
    grid: "Tic Tac Toe",
  },
  archive: { title: "Önceki günler", played: (s) => `${s} puan`, inProgress: "Devam ediyor", notPlayed: "Oynanmadı", today: "Bugün", back: "Geri" },
  shareText: (n, score, grid, url) => `Futbol Mayın Tarlası #${n} — ${score} puan\n${grid}\nBeni geçebilir misin? ${url}`,
  report: "Hata bildir",
  reported: "Teşekkürler! Kontrol edeceğiz.",
  exit: "Çık",
  loading: "Tahta yükleniyor…",
  loadError: "Tahta yüklenemedi. Biraz sonra tekrar dene.",
  retry: "Tekrar dene",
  actionError: "Bağlantı koptu. Tekrar dene.",
  restarted: "Oyunun değişti (başka cihaz veya düzeltme). Yeniden yükledik.",
  dayOver: "Arjantin'de gün bitti: yeni tahta hazır.",
  guestYesterday: "Dünün tahtasını oynuyorsun. Bugününkünü oynamak ve sıralamaya girmek için hesap oluştur.",
  playToday: "Bugününkünü oyna",
  maintenance: "Oyun bakımda. Birazdan tekrar dene.",
  sessionChanged: "Oturumun değişti. Tahtaya yeniden başla.",
  board: {
    title: "Günün sıralaması",
    players: (n) => `${n} oyuncu bitirdi`,
    empty: "Bugünün tahtasını henüz kimse bitirmedi. İlk sen ol!",
    you: "Sen",
    rank: (r) => `Sıra #${r}`,
    join: "Günün sıralamasına girmek için hesap oluştur",
    joinButton: "Sıralamaya gir",
    unranked: "Önceki günler sıralamaya sayılmaz.",
    guestPlay: "Misafir olarak oynuyorsun: puanın sıralamaya girmez.",
  },
};

export const buscaminasCopy = (locale: string): Copy => (locale === "es" ? es : locale === "ka" ? ka : locale === "tr" ? tr : en);
/** Prompts ship in es/en and, from content v2, ka/tr; a missing locale falls back to English. */
export const promptFor = (prompt: { es: string; en: string; ka?: string; tr?: string }, locale: string) =>
  (locale === "es" ? prompt.es : locale === "ka" ? prompt.ka : locale === "tr" ? prompt.tr : undefined) ?? prompt.en;
